insert into dbo.Countries(name) values('Afghanistan');
insert into dbo.Countries(name) values('Albania');
insert into dbo.Countries(name) values('Algeria');
insert into dbo.Countries(name) values('American Samoa');
insert into dbo.Countries(name) values('Andorra');
insert into dbo.Countries(name) values('Angola');
insert into dbo.Countries(name) values('Anguilla');
insert into dbo.Countries(name) values('Antigua & Barbuda');
insert into dbo.Countries(name) values('Argentina');
insert into dbo.Countries(name) values('Armenia');
insert into dbo.Countries(name) values('Aruba');
insert into dbo.Countries(name) values('Australia');
insert into dbo.Countries(name) values('Austria');
insert into dbo.Countries(name) values('Azerbaijan');
insert into dbo.Countries(name) values('Bahamas, The');
insert into dbo.Countries(name) values('Bahrain');
insert into dbo.Countries(name) values('Bangladesh');
insert into dbo.Countries(name) values('Barbados');
insert into dbo.Countries(name) values('Belarus');
insert into dbo.Countries(name) values('Belgium');
insert into dbo.Countries(name) values('Belize');
insert into dbo.Countries(name) values('Benin');
insert into dbo.Countries(name) values('Bermuda');
insert into dbo.Countries(name) values('Bhutan');
insert into dbo.Countries(name) values('Bolivia');
insert into dbo.Countries(name) values('Bosnia & Herzegovina');
insert into dbo.Countries(name) values('Botswana');
insert into dbo.Countries(name) values('Brazil');
insert into dbo.Countries(name) values('British Virgin Is.');
insert into dbo.Countries(name) values('Brunei');
insert into dbo.Countries(name) values('Bulgaria');
insert into dbo.Countries(name) values('Burkina Faso');
insert into dbo.Countries(name) values('Burma');
insert into dbo.Countries(name) values('Burundi');
insert into dbo.Countries(name) values('Cambodia');
insert into dbo.Countries(name) values('Cameroon');
insert into dbo.Countries(name) values('Canada');
insert into dbo.Countries(name) values('Cape Verde');
insert into dbo.Countries(name) values('Cayman Islands');
insert into dbo.Countries(name) values('Central African Rep.');
insert into dbo.Countries(name) values('Chad');
insert into dbo.Countries(name) values('Chile');
insert into dbo.Countries(name) values('China');
insert into dbo.Countries(name) values('Colombia');
insert into dbo.Countries(name) values('Comoros');
insert into dbo.Countries(name) values('Congo, Dem. Rep.');
insert into dbo.Countries(name) values('Congo, Repub. of the');
insert into dbo.Countries(name) values('Cook Islands');
insert into dbo.Countries(name) values('Costa Rica');
insert into dbo.Countries(name) values('Cote d''Ivoire');
insert into dbo.Countries(name) values('Croatia');
insert into dbo.Countries(name) values('Cuba');
insert into dbo.Countries(name) values('Cyprus');
insert into dbo.Countries(name) values('Czech Republic');
insert into dbo.Countries(name) values('Denmark');
insert into dbo.Countries(name) values('Djibouti');
insert into dbo.Countries(name) values('Dominica');
insert into dbo.Countries(name) values('Dominican Republic');
insert into dbo.Countries(name) values('East Timor');
insert into dbo.Countries(name) values('Ecuador');
insert into dbo.Countries(name) values('Egypt');
insert into dbo.Countries(name) values('El Salvador');
insert into dbo.Countries(name) values('Equatorial Guinea');
insert into dbo.Countries(name) values('Eritrea');
insert into dbo.Countries(name) values('Estonia');
insert into dbo.Countries(name) values('Ethiopia');
insert into dbo.Countries(name) values('Faroe Islands');
insert into dbo.Countries(name) values('Fiji');
insert into dbo.Countries(name) values('Finland');
insert into dbo.Countries(name) values('France');
insert into dbo.Countries(name) values('French Guiana');
insert into dbo.Countries(name) values('French Polynesia');
insert into dbo.Countries(name) values('Gabon');
insert into dbo.Countries(name) values('Gambia, The');
insert into dbo.Countries(name) values('Gaza Strip');
insert into dbo.Countries(name) values('Georgia');
insert into dbo.Countries(name) values('Germany');
insert into dbo.Countries(name) values('Ghana');
insert into dbo.Countries(name) values('Gibraltar');
insert into dbo.Countries(name) values('Greece');
insert into dbo.Countries(name) values('Greenland');
insert into dbo.Countries(name) values('Grenada');
insert into dbo.Countries(name) values('Guadeloupe');
insert into dbo.Countries(name) values('Guam');
insert into dbo.Countries(name) values('Guatemala');
insert into dbo.Countries(name) values('Guernsey');
insert into dbo.Countries(name) values('Guinea');
insert into dbo.Countries(name) values('Guinea-Bissau');
insert into dbo.Countries(name) values('Guyana');
insert into dbo.Countries(name) values('Haiti');
insert into dbo.Countries(name) values('Honduras');
insert into dbo.Countries(name) values('Hong Kong');
insert into dbo.Countries(name) values('Hungary');
insert into dbo.Countries(name) values('Iceland');
insert into dbo.Countries(name) values('India');
insert into dbo.Countries(name) values('Indonesia');
insert into dbo.Countries(name) values('Iran');
insert into dbo.Countries(name) values('Iraq');
insert into dbo.Countries(name) values('Ireland');
insert into dbo.Countries(name) values('Isle of Man');
insert into dbo.Countries(name) values('Israel');
insert into dbo.Countries(name) values('Italy');
insert into dbo.Countries(name) values('Jamaica');
insert into dbo.Countries(name) values('Japan');
insert into dbo.Countries(name) values('Jersey');
insert into dbo.Countries(name) values('Jordan');
insert into dbo.Countries(name) values('Kazakhstan');
insert into dbo.Countries(name) values('Kenya');
insert into dbo.Countries(name) values('Kiribati');
insert into dbo.Countries(name) values('Korea, North');
insert into dbo.Countries(name) values('Korea, South');
insert into dbo.Countries(name) values('Kuwait');
insert into dbo.Countries(name) values('Kyrgyzstan');
insert into dbo.Countries(name) values('Laos');
insert into dbo.Countries(name) values('Latvia');
insert into dbo.Countries(name) values('Lebanon');
insert into dbo.Countries(name) values('Lesotho');
insert into dbo.Countries(name) values('Liberia');
insert into dbo.Countries(name) values('Libya');
insert into dbo.Countries(name) values('Liechtenstein');
insert into dbo.Countries(name) values('Lithuania');
insert into dbo.Countries(name) values('Luxembourg');
insert into dbo.Countries(name) values('Macau');
insert into dbo.Countries(name) values('Macedonia');
insert into dbo.Countries(name) values('Madagascar');
insert into dbo.Countries(name) values('Malawi');
insert into dbo.Countries(name) values('Malaysia');
insert into dbo.Countries(name) values('Maldives');
insert into dbo.Countries(name) values('Mali');
insert into dbo.Countries(name) values('Malta');
insert into dbo.Countries(name) values('Marshall Islands');
insert into dbo.Countries(name) values('Martinique');
insert into dbo.Countries(name) values('Mauritania');
insert into dbo.Countries(name) values('Mauritius');
insert into dbo.Countries(name) values('Mayotte');
insert into dbo.Countries(name) values('Mexico');
insert into dbo.Countries(name) values('Micronesia, Fed. St.');
insert into dbo.Countries(name) values('Moldova');
insert into dbo.Countries(name) values('Monaco');
insert into dbo.Countries(name) values('Mongolia');
insert into dbo.Countries(name) values('Montserrat');
insert into dbo.Countries(name) values('Morocco');
insert into dbo.Countries(name) values('Mozambique');
insert into dbo.Countries(name) values('Namibia');
insert into dbo.Countries(name) values('Nauru');
insert into dbo.Countries(name) values('Nepal');
insert into dbo.Countries(name) values('Netherlands');
insert into dbo.Countries(name) values('Netherlands Antilles');
insert into dbo.Countries(name) values('New Caledonia');
insert into dbo.Countries(name) values('New Zealand');
insert into dbo.Countries(name) values('Nicaragua');
insert into dbo.Countries(name) values('Niger');
insert into dbo.Countries(name) values('Nigeria');
insert into dbo.Countries(name) values('N. Mariana Islands');
insert into dbo.Countries(name) values('Norway');
insert into dbo.Countries(name) values('Oman');
insert into dbo.Countries(name) values('Pakistan');
insert into dbo.Countries(name) values('Palau');
insert into dbo.Countries(name) values('Panama');
insert into dbo.Countries(name) values('Papua New Guinea');
insert into dbo.Countries(name) values('Paraguay');
insert into dbo.Countries(name) values('Peru');
insert into dbo.Countries(name) values('Philippines');
insert into dbo.Countries(name) values('Poland');
insert into dbo.Countries(name) values('Portugal');
insert into dbo.Countries(name) values('Puerto Rico');
insert into dbo.Countries(name) values('Qatar');
insert into dbo.Countries(name) values('Reunion');
insert into dbo.Countries(name) values('Romania');
insert into dbo.Countries(name) values('Russia');
insert into dbo.Countries(name) values('Rwanda');
insert into dbo.Countries(name) values('Saint Helena');
insert into dbo.Countries(name) values('Saint Kitts & Nevis');
insert into dbo.Countries(name) values('Saint Lucia');
insert into dbo.Countries(name) values('St Pierre & Miquelon');
insert into dbo.Countries(name) values('Saint Vincent and the Grenadines');
insert into dbo.Countries(name) values('Samoa');
insert into dbo.Countries(name) values('San Marino');
insert into dbo.Countries(name) values('Sao Tome & Principe');
insert into dbo.Countries(name) values('Saudi Arabia');
insert into dbo.Countries(name) values('Senegal');
insert into dbo.Countries(name) values('Serbia');
insert into dbo.Countries(name) values('Seychelles');
insert into dbo.Countries(name) values('Sierra Leone');
insert into dbo.Countries(name) values('Singapore');
insert into dbo.Countries(name) values('Slovakia');
insert into dbo.Countries(name) values('Slovenia');
insert into dbo.Countries(name) values('Solomon Islands');
insert into dbo.Countries(name) values('Somalia');
insert into dbo.Countries(name) values('South Africa');
insert into dbo.Countries(name) values('Spain');
insert into dbo.Countries(name) values('Sri Lanka');
insert into dbo.Countries(name) values('Sudan');
insert into dbo.Countries(name) values('Suriname');
insert into dbo.Countries(name) values('Swaziland');
insert into dbo.Countries(name) values('Sweden');
insert into dbo.Countries(name) values('Switzerland');
insert into dbo.Countries(name) values('Syria');
insert into dbo.Countries(name) values('Taiwan');
insert into dbo.Countries(name) values('Tajikistan');
insert into dbo.Countries(name) values('Tanzania');
insert into dbo.Countries(name) values('Thailand');
insert into dbo.Countries(name) values('Togo');
insert into dbo.Countries(name) values('Tonga');
insert into dbo.Countries(name) values('Trinidad & Tobago');
insert into dbo.Countries(name) values('Tunisia');
insert into dbo.Countries(name) values('Turkey');
insert into dbo.Countries(name) values('Turkmenistan');
insert into dbo.Countries(name) values('Turks & Caicos Is');
insert into dbo.Countries(name) values('Tuvalu');
insert into dbo.Countries(name) values('Uganda');
insert into dbo.Countries(name) values('Ukraine');
insert into dbo.Countries(name) values('United Arab Emirates');
insert into dbo.Countries(name) values('United Kingdom');
insert into dbo.Countries(name) values('United States');
insert into dbo.Countries(name) values('Uruguay');
insert into dbo.Countries(name) values('Uzbekistan');
insert into dbo.Countries(name) values('Vanuatu');
insert into dbo.Countries(name) values('Venezuela');
insert into dbo.Countries(name) values('Vietnam');
insert into dbo.Countries(name) values('Virgin Islands');
insert into dbo.Countries(name) values('Wallis and Futuna');
insert into dbo.Countries(name) values('West Bank');
insert into dbo.Countries(name) values('Western Sahara');
insert into dbo.Countries(name) values('Yemen');
insert into dbo.Countries(name) values('Zambia');
insert into dbo.Countries(name) values('Zimbabwe');
