insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(55, 'Can you name the tallest 5 mountain peaks in North America?', 4)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Denali (Mount McKinley)', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Logan', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Pico de Orizaba', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Saint Elias', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Volcán Popocatépetl', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Foraker', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Lucania', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Volcán Iztaccíhuatl', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'King Peak', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Bona', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Steele', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(55, 'Mount Blackburn', 0)