declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('1896',1);
insert into @answers(Content, IsCorrect) values('1921',0);
insert into @answers(Content, IsCorrect) values('1723',0);
insert into @answers(Content, IsCorrect) values('1653',0);
exec dbo.InsertQuizQuestion 'Which year did the first Summer Olympic Games start?',5,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Every year',0);
insert into @answers(Content, IsCorrect) values('Every other year',0);
insert into @answers(Content, IsCorrect) values('Every 3 years',0);
insert into @answers(Content, IsCorrect) values('Every 4 years',1);
exec dbo.InsertQuizQuestion 'How often do the Summer Olympic Games occur?',1,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Chicago',0);
insert into @answers(Content, IsCorrect) values('London',1);
insert into @answers(Content, IsCorrect) values('Moscow',0);
insert into @answers(Content, IsCorrect) values('Melbourne',0);
exec dbo.InsertQuizQuestion 'Which city held the most recent (2012) Summer Olympics?',2,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Argentina',0);
insert into @answers(Content, IsCorrect) values('Chile',0);
insert into @answers(Content, IsCorrect) values('Peru',0);
insert into @answers(Content, IsCorrect) values('Brazil',1);
exec dbo.InsertQuizQuestion 'Which country will be hosting the first South American Summer Olympics?',3,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1940 and 1944',1);
insert into @answers(Content, IsCorrect) values('1939 and 1943',0);
insert into @answers(Content, IsCorrect) values('1936 and 1940',0);
insert into @answers(Content, IsCorrect) values('1942 and 1946',0);
exec dbo.InsertQuizQuestion 'Which two Summer Olympics were cancelled due to World War II?',3,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1956',0);
insert into @answers(Content, IsCorrect) values('1960',0);
insert into @answers(Content, IsCorrect) values('1964',1);
insert into @answers(Content, IsCorrect) values('1968',0);
exec dbo.InsertQuizQuestion 'Which year saw the first worldwide televised broadcast of the olympics?',4,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Tokyo',0);
insert into @answers(Content, IsCorrect) values('Munich',1);
insert into @answers(Content, IsCorrect) values('Paris',0);
insert into @answers(Content, IsCorrect) values('Atlanta',0);
exec dbo.InsertQuizQuestion 'Which city hosted the olympics in which a terrorist organization took hostages?',3,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Fancy Diving',1);
insert into @answers(Content, IsCorrect) values('Turnstyle Diving',0);
insert into @answers(Content, IsCorrect) values('Flip Diving',0);
insert into @answers(Content, IsCorrect) values('Deep Diving',0);
exec dbo.InsertQuizQuestion 'When diving was first introduced to the olympics, what was it nicknamed?',5,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('South Korea',0);
insert into @answers(Content, IsCorrect) values('Japan',1);
insert into @answers(Content, IsCorrect) values('China',0);
insert into @answers(Content, IsCorrect) values('Cuba',0);
exec dbo.InsertQuizQuestion 'Which country holds the most gold medals for Judo?',3,19, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Canada',0);
insert into @answers(Content, IsCorrect) values('France',0);
insert into @answers(Content, IsCorrect) values('Germany',1);
insert into @answers(Content, IsCorrect) values('Iran',0);
exec dbo.InsertQuizQuestion 'Which country has hosted the olympics in which handball was introduced and then re-introduced?',5,19, @answers;