declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Challenger Deep',1);
insert into @answers(Content, IsCorrect) values('Deeptown',0);
insert into @answers(Content, IsCorrect) values('Blue Wash',0);
insert into @answers(Content, IsCorrect) values('Sandy Crevice',0);
exec dbo.InsertQuizQuestion 'What is the deepest part of the world''s oceans named?',5,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Atlantic',0);
insert into @answers(Content, IsCorrect) values('Pacific',1);
insert into @answers(Content, IsCorrect) values('Arctic',0);
insert into @answers(Content, IsCorrect) values('Indian',0);
exec dbo.InsertQuizQuestion 'Which ocean contains the deepest part?',3,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',0);
insert into @answers(Content, IsCorrect) values('FALSE',1);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuizQuestion 'Because most light does not reach the bottom of the ocean, there is no abundance of life there. True or false?',3,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Light',0);
insert into @answers(Content, IsCorrect) values('Vibrations',0);
insert into @answers(Content, IsCorrect) values('Floor vents',1);
insert into @answers(Content, IsCorrect) values('Cuddling with each other',0);
exec dbo.InsertQuizQuestion 'How does much of the bottom dwelling life get its energy?',4,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('No vehicle, scuba gear is used',0);
insert into @answers(Content, IsCorrect) values('No vehicle, only simulations',0);
insert into @answers(Content, IsCorrect) values('Probes dropped from boats',0);
insert into @answers(Content, IsCorrect) values('Submarines',1);
exec dbo.InsertQuizQuestion 'What vehicle do people use to explore extremely deep parts of the ocean?',3,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Lighterflow',0);
insert into @answers(Content, IsCorrect) values('Bioluminescence',1);
insert into @answers(Content, IsCorrect) values('Brightitosis',0);
insert into @answers(Content, IsCorrect) values('Glowessence',0);
exec dbo.InsertQuizQuestion 'What is it called when a creature emits its own light?',4,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuizQuestion 'Even at crushing pressures in the bottom of the deepest ocean trenches, starfish can still be found. True or false?',3,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sodium',0);
insert into @answers(Content, IsCorrect) values('Sulfate',0);
insert into @answers(Content, IsCorrect) values('Chloride',1);
insert into @answers(Content, IsCorrect) values('Calcium',0);
exec dbo.InsertQuizQuestion 'What is the most commonly found element in the ocean?',5,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('5,000 ft',0);
insert into @answers(Content, IsCorrect) values('7,000 ft',0);
insert into @answers(Content, IsCorrect) values('13,000 ft',1);
insert into @answers(Content, IsCorrect) values('18,000 ft',0);
exec dbo.InsertQuizQuestion 'What is the average depth of all the world''s oceans?',5,18, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Arctic',1);
insert into @answers(Content, IsCorrect) values('Pacific',0);
insert into @answers(Content, IsCorrect) values('Atlantic',0);
insert into @answers(Content, IsCorrect) values('Indian',0);
exec dbo.InsertQuizQuestion 'Which ocean is the most shallow on average?',4,18, @answers;