declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Strawberry',0);
insert into @answers(Content, IsCorrect) values('Lime',0);
insert into @answers(Content, IsCorrect) values('Plain',1);
insert into @answers(Content, IsCorrect) values('Raspberry',0);
exec dbo.InsertQuizQuestion 'What kind of yogurt is Yogurt?',4,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',0);
insert into @answers(Content, IsCorrect) values('FALSE',1);
exec dbo.InsertQuizQuestion 'Merchandise in the movie was available to purchase afterwards?',2,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('SPOIL''D ROTT ''N'' 1',1);
insert into @answers(Content, IsCorrect) values('RICH BRAT',0);
insert into @answers(Content, IsCorrect) values('12345',0);
insert into @answers(Content, IsCorrect) values('PRINCESS',0);
exec dbo.InsertQuizQuestion 'What did Princess Vespa''s Mercedes license plate read?',4,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Dark Helmet show up',0);
insert into @answers(Content, IsCorrect) values('Barf interrupts them',0);
insert into @answers(Content, IsCorrect) values('Yogurt appears',0);
insert into @answers(Content, IsCorrect) values('Dot''s virgin alarm goes off',1);
exec dbo.InsertQuizQuestion 'When Princess Vespa and Lonestar try to kiss, what happens?',3,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('10000',1);
insert into @answers(Content, IsCorrect) values('15000',0);
insert into @answers(Content, IsCorrect) values('20000',0);
insert into @answers(Content, IsCorrect) values('25000',0);
exec dbo.InsertQuizQuestion 'How many years of fresh air is there on Planet Druidia?',5,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2000',0);
insert into @answers(Content, IsCorrect) values('2001',1);
insert into @answers(Content, IsCorrect) values('2015',0);
insert into @answers(Content, IsCorrect) values('2020',0);
exec dbo.InsertQuizQuestion 'What is the model year of Princess Vespa''s Mercedes Benz?',3,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1',0);
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('3',1);
insert into @answers(Content, IsCorrect) values('5',0);
exec dbo.InsertQuizQuestion 'How many minutes are given to evacuate "Spaceball 1" after the self-destruct button is activated?',4,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Ten',0);
insert into @answers(Content, IsCorrect) values('Eleven',1);
insert into @answers(Content, IsCorrect) values('Twelve ',0);
insert into @answers(Content, IsCorrect) values('Twenty',0);
exec dbo.InsertQuizQuestion 'What chapter of the Spaceballs saga does this film show?',4,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Prince Charming',0);
insert into @answers(Content, IsCorrect) values('Prince Valium',1);
insert into @answers(Content, IsCorrect) values('Prince Advil',0);
insert into @answers(Content, IsCorrect) values('Prince Bullock',0);
exec dbo.InsertQuizQuestion 'Who was Princess Vespa originally supposed to marry?',3,13, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bar Mitzvah',0);
insert into @answers(Content, IsCorrect) values('Poker',0);
insert into @answers(Content, IsCorrect) values('Baptism',0);
insert into @answers(Content, IsCorrect) values('Bingo',1);
exec dbo.InsertQuizQuestion 'What is happening at the church the day after Vespa''s wedding?',3,13, @answers;