declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Sam was his friend',0);
insert into @answers(Content, IsCorrect) values('Sam was his gardener',1);
insert into @answers(Content, IsCorrect) values('Sam was his sports team mate',0);
insert into @answers(Content, IsCorrect) values('Sam was his brother',0);
exec dbo.InsertQuizQuestion 'How did Frodo originally know Samwise?',2,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bree',1);
insert into @answers(Content, IsCorrect) values('Rivendell',0);
insert into @answers(Content, IsCorrect) values('The Shire',0);
insert into @answers(Content, IsCorrect) values('Mount Doom',0);
exec dbo.InsertQuizQuestion 'Where did Gandalf first want Frodo to take the ring?',2,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Brandybuck',0);
insert into @answers(Content, IsCorrect) values('Proudfeet',0);
insert into @answers(Content, IsCorrect) values('Took',1);
insert into @answers(Content, IsCorrect) values('Underhill',0);
exec dbo.InsertQuizQuestion 'What was Pippin''s last name?',3,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sam',0);
insert into @answers(Content, IsCorrect) values('Gandalf',0);
insert into @answers(Content, IsCorrect) values('Gollum',0);
insert into @answers(Content, IsCorrect) values('Boromir',1);
exec dbo.InsertQuizQuestion 'Who first tried to take the ring from Frodo?',3,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Orthanc',0);
insert into @answers(Content, IsCorrect) values('Balrog',1);
insert into @answers(Content, IsCorrect) values('Saruman',0);
insert into @answers(Content, IsCorrect) values('Shelob',0);
exec dbo.InsertQuizQuestion 'What was the name of the creature under the mountaint hat was woken up by the Fellowship?',3,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('To avoid Saruman''s spells',1);
insert into @answers(Content, IsCorrect) values('To keep warm',0);
insert into @answers(Content, IsCorrect) values('To meet Gimli''s family',0);
insert into @answers(Content, IsCorrect) values('Because Frodo likes caves',0);
exec dbo.InsertQuizQuestion 'Why did the Fellowship take the path under the mountain?',2,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Gandalf was weak minded',0);
insert into @answers(Content, IsCorrect) values('Saruman was controlled by Sauron',1);
insert into @answers(Content, IsCorrect) values('Saruman wanted to control Middle Earth',0);
insert into @answers(Content, IsCorrect) values('Gandlalf convinced him to betry himself as a part of a greater plan',0);
exec dbo.InsertQuizQuestion 'Why did Saruman betray Gandalf?',2,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Gollum told him through torture',0);
insert into @answers(Content, IsCorrect) values('Frodo wore the ring in The Shire',0);
insert into @answers(Content, IsCorrect) values('Gollum told him through torture',1);
insert into @answers(Content, IsCorrect) values('The Ringwraiths found it by chance',0);
exec dbo.InsertQuizQuestion 'How did Sauron learn that the ring was in The Shire?',4,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Murkwood',1);
insert into @answers(Content, IsCorrect) values('Lothlorien',0);
insert into @answers(Content, IsCorrect) values('Rivendell',0);
insert into @answers(Content, IsCorrect) values('Gondor',0);
exec dbo.InsertQuizQuestion 'Where was Legolas from?',4,26, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('The Ranger',0);
insert into @answers(Content, IsCorrect) values('Strider',1);
insert into @answers(Content, IsCorrect) values('Bullseye',0);
insert into @answers(Content, IsCorrect) values('Hawkeye',0);
exec dbo.InsertQuizQuestion 'What was Aragorn''s nickname that he used to stay anonymous?',2,26, @answers;