insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(40, 'The Bluth family is a disaster. Can you sort them out by picking the correct names?', 2)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Lindsay', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Tobias', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'George Sr', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Gob', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Michael', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'George-Michael', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Lucille', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Maebe', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Buster', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Oscar', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Lucille 2', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Hermano', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Sitwell', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Franklin', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Judge', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Bob', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(40, 'Barry', 0)
