declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Second',0);
insert into @answers(Content, IsCorrect) values('Fourth',1);
insert into @answers(Content, IsCorrect) values('Fifth',0);
insert into @answers(Content, IsCorrect) values('Seventh',0);
exec dbo.InsertQuizQuestion 'Harry Potter and the Goblet of Fire is which number book in the series?',1,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Outstanding Wizarding Levels',0);
insert into @answers(Content, IsCorrect) values('Outstanding Wizarding License',0);
insert into @answers(Content, IsCorrect) values('Ordinary Wizarding Levels',1);
insert into @answers(Content, IsCorrect) values('Ordinary Wizarding License',0);
exec dbo.InsertQuizQuestion 'What does O.W.L. stand for?',4,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('30th of June',0);
insert into @answers(Content, IsCorrect) values('31st of July',1);
insert into @answers(Content, IsCorrect) values('31st of August',0);
insert into @answers(Content, IsCorrect) values('30th of September',0);
exec dbo.InsertQuizQuestion 'When is Harry Potter''s birthday?',3,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Nine',0);
insert into @answers(Content, IsCorrect) values('Ten',0);
insert into @answers(Content, IsCorrect) values('Eleven',1);
insert into @answers(Content, IsCorrect) values('Twelve',0);
exec dbo.InsertQuizQuestion 'How old is Harry in Harry Potter and the Philospher''s Stone?',3,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Badger',1);
insert into @answers(Content, IsCorrect) values('Lion',0);
insert into @answers(Content, IsCorrect) values('Gerbal',0);
insert into @answers(Content, IsCorrect) values('Pig',0);
exec dbo.InsertQuizQuestion 'What is the symbol for Hufflepuff''s house?',2,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Riddle',0);
insert into @answers(Content, IsCorrect) values('Potter',0);
insert into @answers(Content, IsCorrect) values('Clearwater',0);
insert into @answers(Content, IsCorrect) values('Gaunt',1);
exec dbo.InsertQuizQuestion 'What was Tom Riddle''s mother''s maiden name?',4,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Phoenix Tears',1);
insert into @answers(Content, IsCorrect) values('Dragons Blood',0);
insert into @answers(Content, IsCorrect) values('Wormroot',0);
insert into @answers(Content, IsCorrect) values('Mandrake Root',0);
exec dbo.InsertQuizQuestion 'What is the only antidote to Basilisk venom?',4,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('3',0);
insert into @answers(Content, IsCorrect) values('4',0);
insert into @answers(Content, IsCorrect) values('5',1);
exec dbo.InsertQuizQuestion 'How many brothers does Ron Weasley have?',2,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('3',0);
insert into @answers(Content, IsCorrect) values('6',1);
insert into @answers(Content, IsCorrect) values('8',0);
exec dbo.InsertQuizQuestion 'How many goal posts are there on a Quidditch pitch?',2,12, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Volkswagen Beetle',0);
insert into @answers(Content, IsCorrect) values('Ford Anglia',1);
insert into @answers(Content, IsCorrect) values('Aston Martin',0);
insert into @answers(Content, IsCorrect) values('Buick',0);
exec dbo.InsertQuizQuestion 'What type of car is Mr. Weasley''s flying car?',2,12, @answers;