insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(57, 'Can you name the tallest 5 mountain peaks in Asia?', 4)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Mount Everest', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'K2', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Kangchenjunga', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Lhotse', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Makalu', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Cho Oyu', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Dhaulagiri I', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Manaslu', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Nanga Parbat', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Annapurna I', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Gasherbrum I', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(57, 'Broad Peak', 0)