declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Celestial objects',1);
insert into @answers(Content, IsCorrect) values('Periodic elements',0);
insert into @answers(Content, IsCorrect) values('Human history',0);
insert into @answers(Content, IsCorrect) values('Rock formations',0);
exec dbo.InsertQuestion 'Astronomy is the study of what?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuestion 'Amateur astronomers play an active role in discovering new objects in the universe. True or false?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Study of rock formations',0);
insert into @answers(Content, IsCorrect) values('Study of prophecies',0);
insert into @answers(Content, IsCorrect) values('Religion of peace',0);
insert into @answers(Content, IsCorrect) values('Law of the stars',1);
exec dbo.InsertQuestion 'The word ''astronomy'' means what?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sun is the center of the universe',0);
insert into @answers(Content, IsCorrect) values('Earth is the center of the universe',1);
insert into @answers(Content, IsCorrect) values('Earth is the center of the solar system',0);
insert into @answers(Content, IsCorrect) values('The universe is expanding',0);
exec dbo.InsertQuestion 'What is the geocentric model of the universe?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Babylonian',1);
insert into @answers(Content, IsCorrect) values('Sumerian',0);
insert into @answers(Content, IsCorrect) values('Greek',0);
insert into @answers(Content, IsCorrect) values('Ottomans',0);
exec dbo.InsertQuestion 'Which civilization discovered the concept of the lunar eclipse?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sun is the center of the universe',0);
insert into @answers(Content, IsCorrect) values('Earth is the center of the universe',0);
insert into @answers(Content, IsCorrect) values('Earth is the center of the solar system',0);
insert into @answers(Content, IsCorrect) values('Sun is the center of the solar system',1);
exec dbo.InsertQuestion 'What is the heliocentric model of the solar system?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Scalpal',0);
insert into @answers(Content, IsCorrect) values('Screwdriver',0);
insert into @answers(Content, IsCorrect) values('Telescope',1);
insert into @answers(Content, IsCorrect) values('Computer',0);
exec dbo.InsertQuestion 'Galileo is most famous for using what astronomical instrument?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Iron and Carbon',0);
insert into @answers(Content, IsCorrect) values('Hydrogen and Helium',1);
insert into @answers(Content, IsCorrect) values('Oxygen and Nitrogen',0);
insert into @answers(Content, IsCorrect) values('Xenon and Radon',0);
exec dbo.InsertQuestion 'At the center of stars, the process of thermonuclear fusion takes place between which two elements?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Nebula',1);
insert into @answers(Content, IsCorrect) values('Black hole',0);
insert into @answers(Content, IsCorrect) values('Galaxy',0);
insert into @answers(Content, IsCorrect) values('Comet tail',0);
exec dbo.InsertQuestion 'In what celestial object are stars born?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('White dwarf',1);
insert into @answers(Content, IsCorrect) values('Red giant',0);
exec dbo.InsertQuestion 'Which type of star is older, a white dwarf or a red giant?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Group',0);
insert into @answers(Content, IsCorrect) values('Collection',0);
insert into @answers(Content, IsCorrect) values('Constellation',1);
insert into @answers(Content, IsCorrect) values('Party',0);
exec dbo.InsertQuestion 'A formation of stars in the observable sky from Earth are often called what?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Alpha Centauri',1);
insert into @answers(Content, IsCorrect) values('Sirius',0);
insert into @answers(Content, IsCorrect) values('Betelgeuse',0);
insert into @answers(Content, IsCorrect) values('Aldeberon',0);
exec dbo.InsertQuestion 'Which star system is the closest to Earth?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
exec dbo.InsertQuestion 'Earth is the third planet from the Sun. True or false?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('225',0);
insert into @answers(Content, IsCorrect) values('550',0);
insert into @answers(Content, IsCorrect) values('365',1);
insert into @answers(Content, IsCorrect) values('741',0);
exec dbo.InsertQuestion 'Approximately how many times per year does the Earth rotate on its own axis?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1',1);
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('3',0);
insert into @answers(Content, IsCorrect) values('4',0);
exec dbo.InsertQuestion 'How many times per year does the Earth revolve around the Sun?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('The moon''s gravity',1);
insert into @answers(Content, IsCorrect) values('The Earth''s magnetic field',0);
insert into @answers(Content, IsCorrect) values('Magic',0);
insert into @answers(Content, IsCorrect) values('Tectonic plate shifting',0);
exec dbo.InsertQuestion 'What causes the Earth''s tides?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('30%',0);
insert into @answers(Content, IsCorrect) values('99%',1);
insert into @answers(Content, IsCorrect) values('95%',0);
insert into @answers(Content, IsCorrect) values('75%',0);
exec dbo.InsertQuestion 'It is estimated that what percent of all life on Earth has gone extinct?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Rocks',1);
insert into @answers(Content, IsCorrect) values('Oceans',0);
insert into @answers(Content, IsCorrect) values('Insects',0);
insert into @answers(Content, IsCorrect) values('Lions',0);
exec dbo.InsertQuestion 'Geology is the study of what?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Inner core',0);
insert into @answers(Content, IsCorrect) values('Outer core',0);
insert into @answers(Content, IsCorrect) values('Upper mantle',0);
insert into @answers(Content, IsCorrect) values('Crust',1);
exec dbo.InsertQuestion 'Which layer is the outermost layer of the Earth?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Hurricanes',0);
insert into @answers(Content, IsCorrect) values('Tornados',0);
insert into @answers(Content, IsCorrect) values('Earthquakes',0);
insert into @answers(Content, IsCorrect) values('Volcanos',1);
exec dbo.InsertQuestion 'Islands are formed as the result of what natural action?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Magnets',0);
insert into @answers(Content, IsCorrect) values('Tectonic plates',1);
insert into @answers(Content, IsCorrect) values('Clouds',0);
insert into @answers(Content, IsCorrect) values('People',0);
exec dbo.InsertQuestion 'Earthquakes are caused by the shifting of what?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
exec dbo.InsertQuestion 'Geology is important to the study of the history of the Earth. True or false?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Karl Landsteiner',1);
insert into @answers(Content, IsCorrect) values('Wilhelm Wundt',0);
insert into @answers(Content, IsCorrect) values('Gustav Fechner',0);
insert into @answers(Content, IsCorrect) values('Ernst Weber',0);
exec dbo.InsertQuestion 'Who discovered the concept of blood types?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Red blood cells',0);
insert into @answers(Content, IsCorrect) values('Insulin',1);
insert into @answers(Content, IsCorrect) values('White blood cells',0);
insert into @answers(Content, IsCorrect) values('Neurons',0);
exec dbo.InsertQuestion 'What does the pancreas create to break down sugars?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('54%',0);
insert into @answers(Content, IsCorrect) values('71%',1);
insert into @answers(Content, IsCorrect) values('89%',0);
insert into @answers(Content, IsCorrect) values('36%',0);
exec dbo.InsertQuestion 'What percent of the Earth is covered by ocean?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('baseball player',0);
insert into @answers(Content, IsCorrect) values('sword fighter',0);
insert into @answers(Content, IsCorrect) values('mortician',1);
insert into @answers(Content, IsCorrect) values('doctor',0);
exec dbo.InsertQuestion 'What does the word nokanshi mean in Japanese?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Incredible accuracy',0);
insert into @answers(Content, IsCorrect) values('Down the middle',0);
insert into @answers(Content, IsCorrect) values('Sideways slider',0);
insert into @answers(Content, IsCorrect) values('Bugs Bunny changeup',1);
exec dbo.InsertQuestion 'Adam Morgan, a pitcher for the Philadelphia Phillies uses what technique as described by his manager?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Showman and businessman',1);
insert into @answers(Content, IsCorrect) values('Chemist',0);
insert into @answers(Content, IsCorrect) values('Sports superstar',0);
insert into @answers(Content, IsCorrect) values('U.S. president',0);
exec dbo.InsertQuestion 'Who was P.T. Barnum?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Worker Day',0);
insert into @answers(Content, IsCorrect) values('Independence Day',0);
insert into @answers(Content, IsCorrect) values('Children''s Day',0);
insert into @answers(Content, IsCorrect) values('Resting Day',1);
exec dbo.InsertQuestion 'What is the name of the day on August 16 in Paraguay?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Uses Hermione''s Wands',0);
insert into @answers(Content, IsCorrect) values('Uses the Elder Wand',1);
insert into @answers(Content, IsCorrect) values('Dobby helps him',0);
insert into @answers(Content, IsCorrect) values('One of the teachers fixes it',0);
exec dbo.InsertQuestion 'How does Harry fix his wand in the seventh Harry Potter book?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Aurora',0);
insert into @answers(Content, IsCorrect) values('Jasmine',0);
insert into @answers(Content, IsCorrect) values('Snow White',1);
insert into @answers(Content, IsCorrect) values('Cinderella',0);
exec dbo.InsertQuestion 'Who is the youngest Disney princess?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eric',1);
insert into @answers(Content, IsCorrect) values('Adam',0);
insert into @answers(Content, IsCorrect) values('Phillip',0);
insert into @answers(Content, IsCorrect) values('The Price',0);
exec dbo.InsertQuestion 'What is the name of the princess in The Little Mermaid?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eugene Fitzherbert',1);
insert into @answers(Content, IsCorrect) values('Eugene Perry',0);
insert into @answers(Content, IsCorrect) values('Naveen Perry',0);
insert into @answers(Content, IsCorrect) values('Eddy Fitzherbert',0);
exec dbo.InsertQuestion 'What is Flynn Rider''s real name?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuestion 'Elsa and Anna are not official Disney princesses. True or false?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Riku',0);
insert into @answers(Content, IsCorrect) values('Sora',1);
insert into @answers(Content, IsCorrect) values('Kairi',0);
insert into @answers(Content, IsCorrect) values('Mickey Mouse',0);
exec dbo.InsertQuestion 'Who is the main protagonist in Kingdom Hearts.',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Noriko Matsueda',0);
insert into @answers(Content, IsCorrect) values('Nobuo Uematsu',1);
insert into @answers(Content, IsCorrect) values('Masashi Hamauzu',0);
insert into @answers(Content, IsCorrect) values('Naoshi Mizuta',0);
exec dbo.InsertQuestion 'Who composed Final Fantasy VII''s music?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Snow',0);
insert into @answers(Content, IsCorrect) values('Hope',0);
insert into @answers(Content, IsCorrect) values('Serah',0);
insert into @answers(Content, IsCorrect) values('Lightning',1);
exec dbo.InsertQuestion 'Who is the main protagonist in Final Fantasy XIII?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Maya',0);
insert into @answers(Content, IsCorrect) values('Inca',0);
insert into @answers(Content, IsCorrect) values('Aztec',1);
insert into @answers(Content, IsCorrect) values('Zapotec',0);
exec dbo.InsertQuestion 'The word ''tomato'' derives from which ancient civilization?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Tennessee and Ohio',1);
insert into @answers(Content, IsCorrect) values('Florida and Georgia',0);
insert into @answers(Content, IsCorrect) values('Alaska and Hawaii',0);
insert into @answers(Content, IsCorrect) values('Kentucky and West Virginia',0);
exec dbo.InsertQuestion 'The tomato is the state fruit of which two U.S. states?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Dead Poets Society',1);
insert into @answers(Content, IsCorrect) values('Pulp Fiction',0);
insert into @answers(Content, IsCorrect) values('The Godfather',0);
insert into @answers(Content, IsCorrect) values('Patch Adams',0);
exec dbo.InsertQuestion 'Which movie does this quote come from: Carpe diem. Seize the day, boys. Make your lives extraordinary.',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eagle Five',1);
insert into @answers(Content, IsCorrect) values('Falcon One',0);
insert into @answers(Content, IsCorrect) values('Winnebago',0);
insert into @answers(Content, IsCorrect) values('Millennial',0);
exec dbo.InsertQuestion 'What is the name of Lone Starr''s ship in SpaceBalls?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Volcano',0);
insert into @answers(Content, IsCorrect) values('Underwater Earthquake',1);
insert into @answers(Content, IsCorrect) values('Whales',0);
insert into @answers(Content, IsCorrect) values('Whirlpools',0);
exec dbo.InsertQuestion 'What causes a tsunami?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('50',0);
insert into @answers(Content, IsCorrect) values('100',0);
insert into @answers(Content, IsCorrect) values('150',1);
insert into @answers(Content, IsCorrect) values('200',0);
exec dbo.InsertQuestion 'Falling coconuts kill about how many people per year?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('12k',1);
insert into @answers(Content, IsCorrect) values('18k',0);
insert into @answers(Content, IsCorrect) values('22k',0);
insert into @answers(Content, IsCorrect) values('24k',0);
exec dbo.InsertQuestion 'A gold ring that is 50% solid gold and 50% other metals will be rated as how many carats?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Pluto',0);
insert into @answers(Content, IsCorrect) values('Venus',0);
insert into @answers(Content, IsCorrect) values('Uranus',0);
insert into @answers(Content, IsCorrect) values('Jupiter',1);
exec dbo.InsertQuestion 'What planet is named for the most powerful of the Roman gods?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Silicon',1);
insert into @answers(Content, IsCorrect) values('Iron',0);
insert into @answers(Content, IsCorrect) values('Carbon',0);
insert into @answers(Content, IsCorrect) values('Cobalt',0);
exec dbo.InsertQuestion 'Primarily from which chemical element are semiconductors made?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1',0);
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('3',1);
insert into @answers(Content, IsCorrect) values('4',0);
exec dbo.InsertQuestion 'How many Oceans border the United States?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Drug testing',0);
insert into @answers(Content, IsCorrect) values('Designated hitter',1);
insert into @answers(Content, IsCorrect) values('Batter is out when he bunts a foul on the third strike',0);
insert into @answers(Content, IsCorrect) values('Batting out of Turn',0);
exec dbo.InsertQuestion 'What significant change in the basic rules of major league baseball first occurred in the 1973 season, and is still used today?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Dodo',1);
insert into @answers(Content, IsCorrect) values('Elephant Bird',0);
insert into @answers(Content, IsCorrect) values('New Zealand Quail',0);
insert into @answers(Content, IsCorrect) values('Red Rail',0);
exec dbo.InsertQuestion 'What large, clumsy, flightless bird has been extinct for 200 years?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Roger Staubach',0);
insert into @answers(Content, IsCorrect) values('Len Dawson',0);
insert into @answers(Content, IsCorrect) values('Joe Namath',0);
insert into @answers(Content, IsCorrect) values('Bart Starr',1);
exec dbo.InsertQuestion 'Who was the MVP of the first Super Bowl?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Super Bowl V',0);
insert into @answers(Content, IsCorrect) values('Super Bowl VI',1);
insert into @answers(Content, IsCorrect) values('Super Bowl VII',0);
insert into @answers(Content, IsCorrect) values('Super Bowl VII',0);
exec dbo.InsertQuestion 'Which Super Bowl was the Dallas Cowboy''s first win?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bengal ',0);
insert into @answers(Content, IsCorrect) values('Abyssinian',0);
insert into @answers(Content, IsCorrect) values('Balinese',0);
insert into @answers(Content, IsCorrect) values('Siamese',1);
exec dbo.InsertQuestion 'What breed of cat is descended from sacred temple cats from Thailand?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Polydactyl',1);
insert into @answers(Content, IsCorrect) values('Aegean',0);
insert into @answers(Content, IsCorrect) values('American Bobtail',0);
insert into @answers(Content, IsCorrect) values('Balinese',0);
exec dbo.InsertQuestion 'What cat breed has extra toes?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Partitive article',0);
insert into @answers(Content, IsCorrect) values('Indefinite Article',0);
insert into @answers(Content, IsCorrect) values('Definite Article',1);
insert into @answers(Content, IsCorrect) values('Zero article',0);
exec dbo.InsertQuestion 'The word the serves primarily as what part of speech?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bronze Age',1);
insert into @answers(Content, IsCorrect) values('Iron Age',0);
insert into @answers(Content, IsCorrect) values('Metal Age',0);
insert into @answers(Content, IsCorrect) values('Gold Age',0);
exec dbo.InsertQuestion 'What period of human culture followed the Stone Age?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1945',0);
insert into @answers(Content, IsCorrect) values('1947',1);
insert into @answers(Content, IsCorrect) values('1949',0);
insert into @answers(Content, IsCorrect) values('1950',0);
exec dbo.InsertQuestion 'In what year did India gain its independence?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Archery and Golf',0);
insert into @answers(Content, IsCorrect) values('Football and Golf',1);
insert into @answers(Content, IsCorrect) values('Football and Archery',0);
insert into @answers(Content, IsCorrect) values('Golf and Swimming',0);
exec dbo.InsertQuestion 'In 1456, Scottish King James II banned people from playing what two increasingly popular sports?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Pluto',0);
insert into @answers(Content, IsCorrect) values('Venus',0);
insert into @answers(Content, IsCorrect) values('Saturn',1);
insert into @answers(Content, IsCorrect) values('Jupiter',0);
exec dbo.InsertQuestion 'Which planet was named for the mythological father of Zeus?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Abraham Lincoln',1);
insert into @answers(Content, IsCorrect) values('Harry Truman ',0);
insert into @answers(Content, IsCorrect) values('George Washington',0);
insert into @answers(Content, IsCorrect) values('Christopher Lee',0);
exec dbo.InsertQuestion 'Who said, "You can fool all of the people some of the time, and some of the people all of the time, but you can''t fool all the people all the time"?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Pot',0);
insert into @answers(Content, IsCorrect) values('Bread',1);
insert into @answers(Content, IsCorrect) values('Apple',0);
insert into @answers(Content, IsCorrect) values('Orange',0);
exec dbo.InsertQuestion 'What does the Japanese word ''pan'' mean in English?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sticky',0);
insert into @answers(Content, IsCorrect) values('Gum',1);
insert into @answers(Content, IsCorrect) values('Girl',0);
insert into @answers(Content, IsCorrect) values('Toy',0);
exec dbo.InsertQuestion 'What does the Spanish word 'chicle' mean in English?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1987',0);
insert into @answers(Content, IsCorrect) values('1988',0);
insert into @answers(Content, IsCorrect) values('1989',1);
insert into @answers(Content, IsCorrect) values('1990',0);
exec dbo.InsertQuestion 'What year was Taylor Swift born in?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('July 4, 1981',0);
insert into @answers(Content, IsCorrect) values('August 1, 1981',1);
insert into @answers(Content, IsCorrect) values('September 1, 1981',0);
insert into @answers(Content, IsCorrect) values('October 31, 1981',0);
exec dbo.InsertQuestion 'On what date did MTV make it''s debut?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Video Killed The Radio Star',1);
insert into @answers(Content, IsCorrect) values('Back in Black',0);
insert into @answers(Content, IsCorrect) values('I Love Rock and Roll',0);
insert into @answers(Content, IsCorrect) values('Animals',0);
exec dbo.InsertQuestion 'What was the first video ever played on MTV?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Animals',0);
insert into @answers(Content, IsCorrect) values('The Dark Side of the Moon',0);
insert into @answers(Content, IsCorrect) values('The Piper at the Gates of Dawn',1);
insert into @answers(Content, IsCorrect) values('A Saucerful of Secrets',0);
exec dbo.InsertQuestion 'What was Pink Floyd''s first album?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Fergie',0);
insert into @answers(Content, IsCorrect) values('Sarah Ann Ferguson',0);
insert into @answers(Content, IsCorrect) values('Stacy Ann Fergie',0);
insert into @answers(Content, IsCorrect) values('Stacy Ann Ferguson',1);
exec dbo.InsertQuestion 'What is Fergie''s real name?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Kelly Clarkson',1);
insert into @answers(Content, IsCorrect) values('Ruben Studdard',0);
insert into @answers(Content, IsCorrect) values('Carrie Underwood',0);
insert into @answers(Content, IsCorrect) values('Taylor Hicks',0);
exec dbo.InsertQuestion 'Who won American Idol season one?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bruce Marshall Mathers II',0);
insert into @answers(Content, IsCorrect) values('Marshall Bruce Mathers III',1);
insert into @answers(Content, IsCorrect) values('Marshall Bruce Matters III',0);
insert into @answers(Content, IsCorrect) values('Bruce Marshall Matters II',0);
exec dbo.InsertQuestion 'What is Eminem''s real name?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuestion 'Justin Timberlake was a mouseketter?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('10',0);
insert into @answers(Content, IsCorrect) values('12',0);
insert into @answers(Content, IsCorrect) values('13',1);
insert into @answers(Content, IsCorrect) values('14',0);
exec dbo.InsertQuestion 'How many weeks did Hanson''s MMMBop stay at the number one postion?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Dave Grohl',0);
insert into @answers(Content, IsCorrect) values('Dan Peters',0);
insert into @answers(Content, IsCorrect) values('Mark Pickerel',0);
insert into @answers(Content, IsCorrect) values('Chad Channing',1);
exec dbo.InsertQuestion 'Who was the original drummer for Nirvana?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Ohio',0);
insert into @answers(Content, IsCorrect) values('Oklahoma',1);
insert into @answers(Content, IsCorrect) values('Kansas',0);
insert into @answers(Content, IsCorrect) values('None',0);
exec dbo.InsertQuestion 'Which state has the watermelon as their state vegetable?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Gilligan''s Island',1);
insert into @answers(Content, IsCorrect) values('Bewitched',0);
insert into @answers(Content, IsCorrect) values('M*A*S*H',0);
insert into @answers(Content, IsCorrect) values('I Dream of Jeannie',0);
exec dbo.InsertQuestion 'Star Trek: The Original Series was cancelled so this show could stay on the air?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sailor Jupiter',0);
insert into @answers(Content, IsCorrect) values('Sailor Mars',0);
insert into @answers(Content, IsCorrect) values('Sailor Venus',0);
insert into @answers(Content, IsCorrect) values('Sailor Mercury',1);
exec dbo.InsertQuestion 'Amy Anderson is which Sailor Scout in Sailor Moon?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Firefly',0);
insert into @answers(Content, IsCorrect) values('X-Files',0);
insert into @answers(Content, IsCorrect) values('Star Trek: The Next Generation',1);
insert into @answers(Content, IsCorrect) values('Sliders',0);
exec dbo.InsertQuestion 'Many voice actors in the TV Show Gargoyles were actors in what sci-fi TV show?',5,1, @answers;