insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(41, 'Can you name all the countries of South America?', 2)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Argentina', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Bolivia', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Brazil', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Chile', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Colombia', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Ecuador', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'French Guiana', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Guyana', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Paraguya', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Peru', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Suriname', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Uruguay', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Venezuela', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Falkland Islands', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Belize', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Costa Rica', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'El Salvador', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Guatemala', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Honduras', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Nicaragua', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(41, 'Panama', 0)
