declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Celestial objects',1);
insert into @answers(Content, IsCorrect) values('Periodic elements',0);
insert into @answers(Content, IsCorrect) values('Human history',0);
insert into @answers(Content, IsCorrect) values('Rock formations',0);
exec dbo.InsertQuestion 'Astronomy is the study of what?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuestion 'Amateur astronomers play an active role in discovering new objects in the universe. True or false?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Study of rock formations',0);
insert into @answers(Content, IsCorrect) values('Study of prophecies',0);
insert into @answers(Content, IsCorrect) values('Religion of peace',0);
insert into @answers(Content, IsCorrect) values('Law of the stars',1);
exec dbo.InsertQuestion 'The word ''astronomy'' means what?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sun is the center of the universe',0);
insert into @answers(Content, IsCorrect) values('Earth is the center of the universe',1);
insert into @answers(Content, IsCorrect) values('Earth is the center of the solar system',0);
insert into @answers(Content, IsCorrect) values('The universe is expanding',0);
exec dbo.InsertQuestion 'What is the geocentric model of the universe?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Babylonian',1);
insert into @answers(Content, IsCorrect) values('Sumerian',0);
insert into @answers(Content, IsCorrect) values('Greek',0);
insert into @answers(Content, IsCorrect) values('Ottomans',0);
exec dbo.InsertQuestion 'Which civilization discovered the concept of the lunar eclipse?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sun is the center of the universe',0);
insert into @answers(Content, IsCorrect) values('Earth is the center of the universe',0);
insert into @answers(Content, IsCorrect) values('Earth is the center of the solar system',0);
insert into @answers(Content, IsCorrect) values('Sun is the center of the solar system',1);
exec dbo.InsertQuestion 'What is the heliocentric model of the solar system?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Scalpal',0);
insert into @answers(Content, IsCorrect) values('Screwdriver',0);
insert into @answers(Content, IsCorrect) values('Telescope',1);
insert into @answers(Content, IsCorrect) values('Computer',0);
exec dbo.InsertQuestion 'Galileo is most famous for using what astronomical instrument?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Iron and Carbon',0);
insert into @answers(Content, IsCorrect) values('Hydrogen and Helium',1);
insert into @answers(Content, IsCorrect) values('Oxygen and Nitrogen',0);
insert into @answers(Content, IsCorrect) values('Xenon and Radon',0);
exec dbo.InsertQuestion 'At the center of stars, the process of thermonuclear fusion takes place between which two elements?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Nebula',1);
insert into @answers(Content, IsCorrect) values('Black hole',0);
insert into @answers(Content, IsCorrect) values('Galaxy',0);
insert into @answers(Content, IsCorrect) values('Comet tail',0);
exec dbo.InsertQuestion 'In what celestial object are stars born?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('White dwarf',1);
insert into @answers(Content, IsCorrect) values('Red giant',0);
exec dbo.InsertQuestion 'Which type of star is older, a white dwarf or a red giant?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Group',0);
insert into @answers(Content, IsCorrect) values('Collection',0);
insert into @answers(Content, IsCorrect) values('Constellation',1);
insert into @answers(Content, IsCorrect) values('Party',0);
exec dbo.InsertQuestion 'A formation of stars in the observable sky from Earth are often called what?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Alpha Centauri',1);
insert into @answers(Content, IsCorrect) values('Sirius',0);
insert into @answers(Content, IsCorrect) values('Betelgeuse',0);
insert into @answers(Content, IsCorrect) values('Aldeberon',0);
exec dbo.InsertQuestion 'Which star system is the closest to Earth?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
exec dbo.InsertQuestion 'Earth is the third planet from the Sun. True or false?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('225',0);
insert into @answers(Content, IsCorrect) values('550',0);
insert into @answers(Content, IsCorrect) values('365',1);
insert into @answers(Content, IsCorrect) values('741',0);
exec dbo.InsertQuestion 'Approximately how many times per year does the Earth rotate on its own axis?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1',1);
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('3',0);
insert into @answers(Content, IsCorrect) values('4',0);
exec dbo.InsertQuestion 'How many times per year does the Earth revolve around the Sun?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('The moon''s gravity',1);
insert into @answers(Content, IsCorrect) values('The Earth''s magnetic field',0);
insert into @answers(Content, IsCorrect) values('Magic',0);
insert into @answers(Content, IsCorrect) values('Tectonic plate shifting',0);
exec dbo.InsertQuestion 'What causes the Earth''s tides?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('30%',0);
insert into @answers(Content, IsCorrect) values('99%',1);
insert into @answers(Content, IsCorrect) values('95%',0);
insert into @answers(Content, IsCorrect) values('75%',0);
exec dbo.InsertQuestion 'It is estimated that what percent of all life on Earth has gone extinct?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Rocks',1);
insert into @answers(Content, IsCorrect) values('Oceans',0);
insert into @answers(Content, IsCorrect) values('Insects',0);
insert into @answers(Content, IsCorrect) values('Lions',0);
exec dbo.InsertQuestion 'Geology is the study of what?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Inner core',0);
insert into @answers(Content, IsCorrect) values('Outer core',0);
insert into @answers(Content, IsCorrect) values('Upper mantle',0);
insert into @answers(Content, IsCorrect) values('Crust',1);
exec dbo.InsertQuestion 'Which layer is the outermost layer of the Earth?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Hurricanes',0);
insert into @answers(Content, IsCorrect) values('Tornados',0);
insert into @answers(Content, IsCorrect) values('Earthquakes',0);
insert into @answers(Content, IsCorrect) values('Volcanos',1);
exec dbo.InsertQuestion 'Islands are formed as the result of what natural action?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Magnets',0);
insert into @answers(Content, IsCorrect) values('Tectonic plates',1);
insert into @answers(Content, IsCorrect) values('Clouds',0);
insert into @answers(Content, IsCorrect) values('People',0);
exec dbo.InsertQuestion 'Earthquakes are caused by the shifting of what?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
exec dbo.InsertQuestion 'Geology is important to the study of the history of the Earth. True or false?',1,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Karl Landsteiner',1);
insert into @answers(Content, IsCorrect) values('Wilhelm Wundt',0);
insert into @answers(Content, IsCorrect) values('Gustav Fechner',0);
insert into @answers(Content, IsCorrect) values('Ernst Weber',0);
exec dbo.InsertQuestion 'Who discovered the concept of blood types?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Red blood cells',0);
insert into @answers(Content, IsCorrect) values('Insulin',1);
insert into @answers(Content, IsCorrect) values('White blood cells',0);
insert into @answers(Content, IsCorrect) values('Neurons',0);
exec dbo.InsertQuestion 'What does the pancreas create to break down sugars?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('54%',0);
insert into @answers(Content, IsCorrect) values('71%',1);
insert into @answers(Content, IsCorrect) values('89%',0);
insert into @answers(Content, IsCorrect) values('36%',0);
exec dbo.InsertQuestion 'What percent of the Earth is covered by ocean?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('baseball player',0);
insert into @answers(Content, IsCorrect) values('sword fighter',0);
insert into @answers(Content, IsCorrect) values('mortician',1);
insert into @answers(Content, IsCorrect) values('doctor',0);
exec dbo.InsertQuestion 'What does the word nokanshi mean in Japanese?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Incredible accuracy',0);
insert into @answers(Content, IsCorrect) values('Down the middle',0);
insert into @answers(Content, IsCorrect) values('Sideways slider',0);
insert into @answers(Content, IsCorrect) values('Bugs Bunny changeup',1);
exec dbo.InsertQuestion 'Adam Morgan, a pitcher for the Philadelphia Phillies uses what technique as described by his manager?',5,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Showman and businessman',1);
insert into @answers(Content, IsCorrect) values('Chemist',0);
insert into @answers(Content, IsCorrect) values('Sports superstar',0);
insert into @answers(Content, IsCorrect) values('U.S. president',0);
exec dbo.InsertQuestion 'Who was P.T. Barnum?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Worker Day',0);
insert into @answers(Content, IsCorrect) values('Independence Day',0);
insert into @answers(Content, IsCorrect) values('Children''s Day',0);
insert into @answers(Content, IsCorrect) values('Resting Day',1);
exec dbo.InsertQuestion 'What is the name of the day on August 16 in Paraguay?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Uses Hermione''s Wands',0);
insert into @answers(Content, IsCorrect) values('Uses the Elder Wand',1);
insert into @answers(Content, IsCorrect) values('Dobby helps him',0);
insert into @answers(Content, IsCorrect) values('One of the teachers fixes it',0);
exec dbo.InsertQuestion 'How does Harry fix his wand in the seventh Harry Potter book?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Aurora',0);
insert into @answers(Content, IsCorrect) values('Jasmine',0);
insert into @answers(Content, IsCorrect) values('Snow White',1);
insert into @answers(Content, IsCorrect) values('Cinderella',0);
exec dbo.InsertQuestion 'Who is the youngest Disney princess?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eric',1);
insert into @answers(Content, IsCorrect) values('Adam',0);
insert into @answers(Content, IsCorrect) values('Phillip',0);
insert into @answers(Content, IsCorrect) values('The Price',0);
exec dbo.InsertQuestion 'What is the name of the princess in The Little Mermaid?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eugene Fitzherbert',1);
insert into @answers(Content, IsCorrect) values('Eugene Perry',0);
insert into @answers(Content, IsCorrect) values('Naveen Perry',0);
insert into @answers(Content, IsCorrect) values('Eddy Fitzherbert',0);
exec dbo.InsertQuestion 'What is Flynn Rider''s real name?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuestion 'Elsa and Anna are not official Disney princesses. True or false?',2,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Riku',0);
insert into @answers(Content, IsCorrect) values('Sora',1);
insert into @answers(Content, IsCorrect) values('Kairi',0);
insert into @answers(Content, IsCorrect) values('Mickey Mouse',0);
exec dbo.InsertQuestion 'Who is the main protagonist in Kingdom Hearts.',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Noriko Matsueda',0);
insert into @answers(Content, IsCorrect) values('Nobuo Uematsu',1);
insert into @answers(Content, IsCorrect) values('Masashi Hamauzu',0);
insert into @answers(Content, IsCorrect) values('Naoshi Mizuta',0);
exec dbo.InsertQuestion 'Who composed Final Fantasy VII''s music?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Snow',0);
insert into @answers(Content, IsCorrect) values('Hope',0);
insert into @answers(Content, IsCorrect) values('Serah',0);
insert into @answers(Content, IsCorrect) values('Lightning',1);
exec dbo.InsertQuestion 'Who is the main protagonist in Final Fantasy XIII?',3,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Maya',0);
insert into @answers(Content, IsCorrect) values('Inca',0);
insert into @answers(Content, IsCorrect) values('Aztec',1);
insert into @answers(Content, IsCorrect) values('Zapotec',0);
exec dbo.InsertQuestion 'The word ''tomato'' derives from which ancient civilization?',4,1, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Tennessee and Ohio',1);
insert into @answers(Content, IsCorrect) values('Florida and Georgia',0);
insert into @answers(Content, IsCorrect) values('Alaska and Hawaii',1);
insert into @answers(Content, IsCorrect) values('Kentucky and West Virginia',0);
exec dbo.InsertQuestion 'The tomato is the state fruit of which two U.S. states?',3,1, @answers;