insert into dbo.MinefieldQuestions(minefieldquestionid, content, points) values(37, 'Can you select all the capital cities of the United States?', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Montgomery', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Juneau', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Phoenix', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Little Rock', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Sacramento', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Denver', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Hartford', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Dover', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Tallahassee', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Atlanta', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Columbia', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Pierre', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Nashville', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Santa Fe', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Austin', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'New York City', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Los Angeles', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Birmingham', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Anchorage', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Jacksonville', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Miami', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Chicago', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Wichita', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Louisville', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(37, 'Kansas City', 0)
