declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Humans',0);
insert into @answers(Content, IsCorrect) values('Elves',0);
insert into @answers(Content, IsCorrect) values('Dwarves',0);
insert into @answers(Content, IsCorrect) values('Ents',1);
exec dbo.InsertQuizQuestion 'Which creatures ended up finally destroying Saruman''s army?',3,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Rohan',1);
insert into @answers(Content, IsCorrect) values('Gondor',0);
insert into @answers(Content, IsCorrect) values('Mirkwood',0);
insert into @answers(Content, IsCorrect) values('Easterling',0);
exec dbo.InsertQuizQuestion 'What was the name of the region over which King Theoden ruled?',3,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Riders of Rohan',1);
insert into @answers(Content, IsCorrect) values('Hell''s Angels',0);
insert into @answers(Content, IsCorrect) values('Gondor''s Elite',0);
insert into @answers(Content, IsCorrect) values('Champions of Middle Earth',0);
exec dbo.InsertQuizQuestion 'What was the name of hte group in which Eomer was the leader?',3,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Theoden had a bad history with Gandalf',0);
insert into @answers(Content, IsCorrect) values('Sauron was controlling Theoden',0);
insert into @answers(Content, IsCorrect) values('Saruman was controlling Theoden',1);
insert into @answers(Content, IsCorrect) values('Wormtongue had a personal problem with Gandalf',0);
exec dbo.InsertQuizQuestion 'Why was King Theoden acting strange when Gandalf originally greeted him?',2,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Orthanc',0);
insert into @answers(Content, IsCorrect) values('Isengard',1);
insert into @answers(Content, IsCorrect) values('Barad-dur',0);
insert into @answers(Content, IsCorrect) values('Mount Doom',0);
exec dbo.InsertQuizQuestion 'What is the name of Sarumon''s tower?',3,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bristlebark',0);
insert into @answers(Content, IsCorrect) values('Dustyoak',0);
insert into @answers(Content, IsCorrect) values('Mosswood',0);
insert into @answers(Content, IsCorrect) values('Treebeard',1);
exec dbo.InsertQuizQuestion 'Which ent did Merry and Pippin run into in Fangorn Forest?',3,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Helm''s Deep',1);
insert into @answers(Content, IsCorrect) values('Isengard',0);
insert into @answers(Content, IsCorrect) values('Riddimark',0);
insert into @answers(Content, IsCorrect) values('Mordor',0);
exec dbo.InsertQuizQuestion 'Where did the humans of Rohan flee to hide from Saruman''s orcs?',1,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eye of Sauron',1);
insert into @answers(Content, IsCorrect) values('Sarumon''s staff',0);
insert into @answers(Content, IsCorrect) values('Wormtongue''s dagger',0);
insert into @answers(Content, IsCorrect) values('Treebeard''s leaf',0);
exec dbo.InsertQuizQuestion 'Which object does Pippin touch which could have caused Frodo to be revealed?',3,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Aragorn',0);
insert into @answers(Content, IsCorrect) values('Faramir',1);
insert into @answers(Content, IsCorrect) values('Legolas',0);
insert into @answers(Content, IsCorrect) values('Gimli',0);
exec dbo.InsertQuizQuestion 'Who was Boromir''s brother?',1,27, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Narsil',0);
insert into @answers(Content, IsCorrect) values('Glamdring',0);
insert into @answers(Content, IsCorrect) values('Sting',1);
insert into @answers(Content, IsCorrect) values('Orcrist',0);
exec dbo.InsertQuizQuestion 'Which weapon gravely wounds Shelob?',2,27, @answers;