declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Minis Tirith',1);
insert into @answers(Content, IsCorrect) values('Osgiliath',0);
insert into @answers(Content, IsCorrect) values('Barad-dur',0);
insert into @answers(Content, IsCorrect) values('The Shire',0);
exec dbo.InsertQuizQuestion 'Which city had a distinct white tree growing in a coutyard?',2,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Witch-king of Angmar',0);
insert into @answers(Content, IsCorrect) values('Corsair of Umbar',0);
insert into @answers(Content, IsCorrect) values('Witch-king of Angmar',1);
insert into @answers(Content, IsCorrect) values('Saruman',0);
exec dbo.InsertQuizQuestion 'Who was the leader of the Nazgul?',2,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Daughter',0);
insert into @answers(Content, IsCorrect) values('Sister',0);
insert into @answers(Content, IsCorrect) values('Neice',1);
insert into @answers(Content, IsCorrect) values('Mother',0);
exec dbo.InsertQuizQuestion 'How was Eowyn related to King Theoden?',3,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Palantir',0);
insert into @answers(Content, IsCorrect) values('Palantir',1);
insert into @answers(Content, IsCorrect) values('Seeing Crystal',0);
insert into @answers(Content, IsCorrect) values('The Ring',0);
exec dbo.InsertQuizQuestion 'Which tainted object to Denethor use in desperation to assist Gondor?',3,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Eowyn',0);
insert into @answers(Content, IsCorrect) values('Galadriel',0);
insert into @answers(Content, IsCorrect) values('Gandalf',0);
insert into @answers(Content, IsCorrect) values('Eowyn',1);
exec dbo.InsertQuizQuestion 'Who does Faramir fall in love with?',3,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Grima',1);
insert into @answers(Content, IsCorrect) values('Gandalf',0);
insert into @answers(Content, IsCorrect) values('Sauron',0);
insert into @answers(Content, IsCorrect) values('Frodo',0);
exec dbo.InsertQuizQuestion 'Who kills Saruman?',3,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Bears',0);
insert into @answers(Content, IsCorrect) values('Eagles',1);
insert into @answers(Content, IsCorrect) values('Ents',0);
insert into @answers(Content, IsCorrect) values('Wizards',0);
exec dbo.InsertQuizQuestion 'Which creatures save Frood and Sam from Mount Doom after its destruction?',2,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Frodo',0);
insert into @answers(Content, IsCorrect) values('Gollum',1);
insert into @answers(Content, IsCorrect) values('Gandalf',0);
insert into @answers(Content, IsCorrect) values('Sam',0);
exec dbo.InsertQuizQuestion 'Who ultimately destroys The Ring?',3,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('To draw out Sauron''s forces and distract him away from Frodo',1);
insert into @answers(Content, IsCorrect) values('To completely destroy Sauron and end the battles',0);
insert into @answers(Content, IsCorrect) values('He is mind controlled to send his allies to their dooms',0);
insert into @answers(Content, IsCorrect) values('To reach Frodo and Sam quickly',0);
exec dbo.InsertQuizQuestion 'Why did Gandalf propose an assault on Mordor after Minis Tirath was defended?',2,28, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('The Undying Lands',0);
insert into @answers(Content, IsCorrect) values('The Shire',0);
insert into @answers(Content, IsCorrect) values('Minis Tirith',0);
insert into @answers(Content, IsCorrect) values('The Undying Lands',1);
exec dbo.InsertQuizQuestion 'Where does Frodo depart to in the end of the novel?',3,28, @answers;