insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(54, 'Select all of the playable characters from Earthbound.', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Ness', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Paula', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Jeff', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Poo', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Starman', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Pokey', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Pickey', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Barf', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Mom', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Dad', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Dog', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(54, 'Steak', 0)