declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('1924',1);
insert into @answers(Content, IsCorrect) values('1936',0);
insert into @answers(Content, IsCorrect) values('1948',0);
insert into @answers(Content, IsCorrect) values('1992',0);
exec dbo.InsertQuizQuestion 'What year was the first Winter Olympics held?',4,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('China',0);
insert into @answers(Content, IsCorrect) values('South Korea',1);
insert into @answers(Content, IsCorrect) values('Japan',0);
insert into @answers(Content, IsCorrect) values('Russia',0);
exec dbo.InsertQuizQuestion 'Which country will host the 2018 Winter Olympics?',4,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Germany',1);
insert into @answers(Content, IsCorrect) values('France',0);
insert into @answers(Content, IsCorrect) values('Russia',0);
insert into @answers(Content, IsCorrect) values('Sweden',0);
exec dbo.InsertQuizQuestion 'Which of these countries has been banned from the Winter Olympics at certain times?',3,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('German invasion of Poland',1);
insert into @answers(Content, IsCorrect) values('Not enough money to host ',0);
insert into @answers(Content, IsCorrect) values('Pearl Harbor attack',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuizQuestion 'Why was the 1940 Winter Olympics cancelled?',2,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Jumps',0);
insert into @answers(Content, IsCorrect) values('Grace',0);
insert into @answers(Content, IsCorrect) values('Speed',1);
insert into @answers(Content, IsCorrect) values('Style',0);
exec dbo.InsertQuizQuestion 'What is the main goal of Downhill Skiing?',3,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Skates',0);
insert into @answers(Content, IsCorrect) values('Car',0);
insert into @answers(Content, IsCorrect) values('Sled',1);
insert into @answers(Content, IsCorrect) values('Skiis',0);
exec dbo.InsertQuizQuestion 'What vehicle do people ride in when competign in Luge?',2,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('United States',0);
insert into @answers(Content, IsCorrect) values('Finland',1);
insert into @answers(Content, IsCorrect) values('Russia',0);
insert into @answers(Content, IsCorrect) values('Germany',0);
exec dbo.InsertQuizQuestion 'Which country holds the most gold medals for Ski Jumping?',3,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Going too fast',0);
insert into @answers(Content, IsCorrect) values('Going too slow',0);
insert into @answers(Content, IsCorrect) values('Hindering another skater',1);
insert into @answers(Content, IsCorrect) values('Winning too much',0);
exec dbo.InsertQuizQuestion 'What is one way to be disqualified in Speed Skating?',2,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('United States',1);
insert into @answers(Content, IsCorrect) values('France',0);
insert into @answers(Content, IsCorrect) values('Norway',0);
insert into @answers(Content, IsCorrect) values('Japan',0);
exec dbo.InsertQuizQuestion 'Which country has hosted the most Winter Olympics?',3,23, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('4',0);
insert into @answers(Content, IsCorrect) values('6',1);
insert into @answers(Content, IsCorrect) values('8',0);
exec dbo.InsertQuizQuestion 'How many sports were included in the first Winter Olympics?',4,23, @answers;