insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(47, 'Which of these countries are part of the European Union? (not all members are included in this quiz)', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Belgium', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'France', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Italy', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Luxembourg', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Netherlands', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Germany', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Denmark', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'United Kingdom', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Greece', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Portugal', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Spain', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Austria', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Finland', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Sweden', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Norway', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Switzerland', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Ukraine', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Serbia', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Albania', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(47, 'Belarus', 0)