declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('The Karate Kid',1);
insert into @answers(Content, IsCorrect) values('Snatch',0);
insert into @answers(Content, IsCorrect) values('Big Trouble Little China',0);
insert into @answers(Content, IsCorrect) values('Bad Boys',0);
exec dbo.InsertQuizQuestion 'Man who catch fly with chopstick accomplish anything.',3,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Cable Guy',0);
insert into @answers(Content, IsCorrect) values('The Truman Show',1);
insert into @answers(Content, IsCorrect) values('Liar Liar',0);
insert into @answers(Content, IsCorrect) values('Yes Man',0);
exec dbo.InsertQuizQuestion 'In case I don''t see ya, good afternoon, good evening, and good night!',3,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Snatch',1);
insert into @answers(Content, IsCorrect) values('Usual Suspects',0);
insert into @answers(Content, IsCorrect) values('Pulp Fiction',0);
insert into @answers(Content, IsCorrect) values('Lock, Stock and Two Smoking Barrels',0);
exec dbo.InsertQuizQuestion 'Who took the jam out of your doughnut?',4,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Center Stage',0);
insert into @answers(Content, IsCorrect) values('Pretty In Pink',0);
insert into @answers(Content, IsCorrect) values('Dirty Dancing',1);
insert into @answers(Content, IsCorrect) values('Titantic',0);
exec dbo.InsertQuizQuestion 'Nobody puts Baby in a corner.',3,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('The Godfather',0);
insert into @answers(Content, IsCorrect) values('Forest Gump',0);
insert into @answers(Content, IsCorrect) values('Fight Club',0);
insert into @answers(Content, IsCorrect) values('Shawshank Redemption',1);
exec dbo.InsertQuizQuestion 'Get busy living, or get busy dying.',2,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Pulp Fiction',0);
insert into @answers(Content, IsCorrect) values('The Godfather',1);
insert into @answers(Content, IsCorrect) values('Shawshank Redemption',0);
insert into @answers(Content, IsCorrect) values('Fight Club',0);
exec dbo.InsertQuizQuestion 'Great men are not born great, they grow great. ',4,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Harry Potter and the Chamber of Secrets',1);
insert into @answers(Content, IsCorrect) values('Harry Potter and The Order of The Phoenix',0);
insert into @answers(Content, IsCorrect) values('Shawshank Redemption',0);
insert into @answers(Content, IsCorrect) values('The Godfather',0);
exec dbo.InsertQuizQuestion 'It is not our abilities that show what we truly are, it is our choices.',5,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Pulp Fiction',0);
insert into @answers(Content, IsCorrect) values('The Godfather',1);
insert into @answers(Content, IsCorrect) values('Fight Club',0);
insert into @answers(Content, IsCorrect) values('Snatch',0);
exec dbo.InsertQuizQuestion 'I''m gonna make him an offer he can''t refuse.',2,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Planet of the Apes',1);
insert into @answers(Content, IsCorrect) values('Beneath the Planet of the Apes',0);
insert into @answers(Content, IsCorrect) values('Conquest of the Planet of the Apes',0);
insert into @answers(Content, IsCorrect) values('Battle for the Planet of the Apes',0);
exec dbo.InsertQuizQuestion 'Take your stinking paws off me, you damned dirty ape!',1,11, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Patch Adams',0);
insert into @answers(Content, IsCorrect) values('The Truman Show',0);
insert into @answers(Content, IsCorrect) values('The Karate Kid',0);
insert into @answers(Content, IsCorrect) values('Shrek',1);
exec dbo.InsertQuizQuestion 'After a while you learn to ignore the names people call you and just trust who you are.',4,11, @answers;