insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(50, 'Can you select the first ten people to serve as the President of the United States?', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'George Washington', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'John Adams', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Thomas Jefferson', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'James Madison', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'James Monroe', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'John Quincy Adams', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Andrew Jackson', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Martin Van Buren', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'William Henry Harrison', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'John Tyler', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'James Polk', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Zachary Taylor', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Millard Fillmore', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Franklin Pierce', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'James Buchanan', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Abraham Lincoln', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Andrew Johnson', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'Rutherford Hayes', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(50, 'James Garfield', 0)