insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(49, 'Which of these lakes is among the top ten largest lakes in the world by area?', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Caspian Sea', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Superior', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Victoria', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Huron', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Michigan', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Tanganyika', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Baikal', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Great Bear Lake', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Malawi', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Great Slave Lake', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Manitoba', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Nipigon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Great Salt Lake', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Saimaa', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Lake of the Woods', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Khanka', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Nettilling', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Mweru', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(49, 'Albert', 0)