insert into dbo.MinefieldQuestions(minefieldquestionid, content, points) values(39, 'Can you select all the NFL quarterbacks in the Hall of Fame?', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Joe Montana', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Steve Young', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Troy Aikman', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Terry Bradshaw', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Dan Marino', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Warren Moon', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Joe Namath', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Bart Starr', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Roger Staubach', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Bob Waterfield', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Tom Brady', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Brett Favre', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Peyton Manning', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Philip Rivers', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Colin Kaepernick', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Nick Foles', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(39, 'Josh McCown', 0)
