declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Darth Vader',1);
insert into @answers(Content, IsCorrect) values('Darth Maul',0);
insert into @answers(Content, IsCorrect) values('Darth Sidius',0);
insert into @answers(Content, IsCorrect) values('Obi Wan',0);
exec dbo.InsertQuizQuestion 'Anakin Skywalker eventually became who?',1,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Spouses',0);
insert into @answers(Content, IsCorrect) values('Siblings',1);
insert into @answers(Content, IsCorrect) values('Mother / Son',0);
insert into @answers(Content, IsCorrect) values('Friends',0);
exec dbo.InsertQuizQuestion 'Princess Leia and Luke Skywalker were what?',2,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2001: Space Odyssey',0);
insert into @answers(Content, IsCorrect) values('The Hidden Fortress',1);
insert into @answers(Content, IsCorrect) values('Yojimbo',0);
insert into @answers(Content, IsCorrect) values('Lawrence of Arabia',0);
exec dbo.InsertQuizQuestion 'C3PO and R2D2 were characters based on what movie?',4,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Chaotic Evil',0);
insert into @answers(Content, IsCorrect) values('Chaotic Good',0);
insert into @answers(Content, IsCorrect) values('Neutral Good',1);
insert into @answers(Content, IsCorrect) values('True Neutral',0);
exec dbo.InsertQuizQuestion 'What is Han Solo''s Dungeons and Dragons alignment?',3,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Darth Maul',0);
insert into @answers(Content, IsCorrect) values('Luke Skywalker',0);
insert into @answers(Content, IsCorrect) values('Darth Vader',0);
insert into @answers(Content, IsCorrect) values('Qui Gon Jin',1);
exec dbo.InsertQuizQuestion 'Who trained Obi Wan Kenobi?',3,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Red',0);
insert into @answers(Content, IsCorrect) values('Green',0);
insert into @answers(Content, IsCorrect) values('Blue',0);
insert into @answers(Content, IsCorrect) values('Purple',1);
exec dbo.InsertQuizQuestion 'What color was Mace Windu''s lightsaber?',3,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Human',0);
insert into @answers(Content, IsCorrect) values('Wookie',1);
insert into @answers(Content, IsCorrect) values('Ewok',0);
insert into @answers(Content, IsCorrect) values('Droid',0);
exec dbo.InsertQuizQuestion 'What type of creature was Chewbacca?',1,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('He was injured in a battle',1);
insert into @answers(Content, IsCorrect) values('He thought it looked cool',0);
insert into @answers(Content, IsCorrect) values('It gave him super powers',0);
insert into @answers(Content, IsCorrect) values('He was forced to wear it',0);
exec dbo.InsertQuizQuestion 'Why did Darth Vader have to wear a suit?',2,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('650',0);
insert into @answers(Content, IsCorrect) values('900',1);
insert into @answers(Content, IsCorrect) values('1200',0);
insert into @answers(Content, IsCorrect) values('400',0);
exec dbo.InsertQuizQuestion 'Approximately how old is Yoda in The Empire Strikes Back?',4,16, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Ben and Lisa',0);
insert into @answers(Content, IsCorrect) values('Nick and Dorris',0);
insert into @answers(Content, IsCorrect) values('C3PO and R2D2',0);
insert into @answers(Content, IsCorrect) values('Beru and Owen',1);
exec dbo.InsertQuizQuestion 'What were Luke Skywalker''s aunt and uncle named?',3,16, @answers;