insert into dbo.MinefieldQuestions(minefieldquestionid, content, points) values(36, 'Can you select all the colors that appear in a rainbow? Think back to early science classes.', 1)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Red', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Orange', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Yellow', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Green', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Blue', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Indigo', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Violet', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Pink', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Purple', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Magenta', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Tangerine', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Black', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'White', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Brown', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Gray', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Ruby', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Bronze', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Crimson', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Fuchsia', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Lime', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Cobalt', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Candy', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Scarlet', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Coral', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(36, 'Cyan', 0)
