declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Penguin',0);
insert into @answers(Content, IsCorrect) values('Ostrich',1);
insert into @answers(Content, IsCorrect) values('Bald Eagle',0);
insert into @answers(Content, IsCorrect) values('Osprey',0);
exec dbo.InsertQuizQuestion 'The emu is the second largest living bird. What''s the largest?',3,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2',0);
insert into @answers(Content, IsCorrect) values('4',0);
insert into @answers(Content, IsCorrect) values('6',0);
insert into @answers(Content, IsCorrect) values('8',1);
exec dbo.InsertQuizQuestion 'All arachnids have how many legs?',2,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Cats',0);
insert into @answers(Content, IsCorrect) values('Dogs',0);
insert into @answers(Content, IsCorrect) values('Rabbits',1);
insert into @answers(Content, IsCorrect) values('Kiwis',0);
exec dbo.InsertQuizQuestion 'Stoats were introduced to New Zealand to control which species?',5,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Termites',0);
insert into @answers(Content, IsCorrect) values('Mantises',1);
insert into @answers(Content, IsCorrect) values('Flies',0);
insert into @answers(Content, IsCorrect) values('Ants',0);
exec dbo.InsertQuizQuestion 'Which insect was believed to have supernatural powers by some early civilizations?',4,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('They might not adjust to home life and become depressed',0);
insert into @answers(Content, IsCorrect) values('They may escape, become invasive, and threaten local animal populations',1);
insert into @answers(Content, IsCorrect) values('Your friends might make fun of you',0);
insert into @answers(Content, IsCorrect) values('The price might be too expensive',0);
exec dbo.InsertQuizQuestion 'What is one of the main threats of taking an exotic animal as a pet?',2,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Land',0);
insert into @answers(Content, IsCorrect) values('Sky',0);
insert into @answers(Content, IsCorrect) values('Water',1);
exec dbo.InsertQuizQuestion 'Does an axolotl live on land, in the sky, or in water?',5,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Omnivores',1);
insert into @answers(Content, IsCorrect) values('Herbivores',0);
insert into @answers(Content, IsCorrect) values('Carnivores',0);
exec dbo.InsertQuizQuestion 'Are jackals omnivores, herbivores, or carnivores?',3,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('North America',0);
insert into @answers(Content, IsCorrect) values('South America',0);
insert into @answers(Content, IsCorrect) values('Africa',1);
insert into @answers(Content, IsCorrect) values('Europe',0);
exec dbo.InsertQuizQuestion 'Genets are most commonly found on what continent?',5,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('To conserve energy during tough times',1);
insert into @answers(Content, IsCorrect) values('Because they are sleepy',0);
insert into @answers(Content, IsCorrect) values('To trick their prey into their nests',0);
exec dbo.InsertQuizQuestion 'Why do some animals go into hibernation?',1,20, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Crows',0);
insert into @answers(Content, IsCorrect) values('Parrots',1);
insert into @answers(Content, IsCorrect) values('Jays',0);
insert into @answers(Content, IsCorrect) values('Magpies',0);
exec dbo.InsertQuizQuestion 'Which type of bird has undergone more exploitation than any other group?',4,20, @answers;