insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(53, 'Select all of the playable characters from Final Fantasy VII.', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Cloud', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Tifa', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Aeris', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Barret', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Red XIII', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Cait Sith', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Cid', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Yuffie', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Vincent', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Sephiroth', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Rod', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Gun', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Cecil', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Zack', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Setzer', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Rude', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Jenova', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Zidane', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Vivi', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Squall', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(53, 'Rufus', 0)