insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(45, 'What do all the letters in PEMDAS stand for?', 2)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Parenthesis', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Exponent', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Multiplication', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Division', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Addition', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Subtraction', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Pascal', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Substantiate', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Subverse', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Math', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Diagonal', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Angle', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Ethereal', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Pictoral', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Polygon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Derivative', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Sine', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(45, 'Arctangent', 0)
