delete from @answers;
insert into @answers(Content, IsCorrect) values('England',0);
insert into @answers(Content, IsCorrect) values('France',1);
insert into @answers(Content, IsCorrect) values('Germany',0);
insert into @answers(Content, IsCorrect) values('Canada',0);
exec dbo.InsertQuizQuestion 'According to Edwin Jenner, doctors in what country came close to finding a cure?',3,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Mary and Gareth',1);
insert into @answers(Content, IsCorrect) values('The Govenor',0);
insert into @answers(Content, IsCorrect) values('Alex and Gareth',0);
insert into @answers(Content, IsCorrect) values('Mary and Alex',0);
exec dbo.InsertQuizQuestion 'Who are the leaders at Terminus?',3,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sheriff Deputy',1);
insert into @answers(Content, IsCorrect) values('Mall Cop',0);
insert into @answers(Content, IsCorrect) values('Security Guard',0);
insert into @answers(Content, IsCorrect) values('Homicide Detective',0);
exec dbo.InsertQuizQuestion 'What was Ricks job before the event?',2,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Atlanta, Georgia',0);
insert into @answers(Content, IsCorrect) values('Raleigh, North Carolina',0);
insert into @answers(Content, IsCorrect) values('Savanah, Georgia',0);
insert into @answers(Content, IsCorrect) values('Alexandria, Virginia',1);
exec dbo.InsertQuizQuestion 'Where does the second half of Season 5 take place?',2,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Every survivor is infected with the walker pathogen and will reanimate after death.',1);
insert into @answers(Content, IsCorrect) values('Every survivor is infected with the walker pathogen but will not reanimate after death unless bit.',0);
insert into @answers(Content, IsCorrect) values('Every survivor is immune to the walker pathogen.',0);
insert into @answers(Content, IsCorrect) values('There is no cure.',0);
exec dbo.InsertQuizQuestion 'What did Dr. Jenner tell Rick when he whispered in his ear?',2,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('A hospital',0);
insert into @answers(Content, IsCorrect) values('A geterinarian',0);
insert into @answers(Content, IsCorrect) values('A high school',1);
insert into @answers(Content, IsCorrect) values('An emergency Room',0);
exec dbo.InsertQuizQuestion 'After Carl is shot, where do Otis and Shane go to get medical supplies?',2,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('A comic',1);
insert into @answers(Content, IsCorrect) values('A novel',0);
insert into @answers(Content, IsCorrect) values('A movie',0);
insert into @answers(Content, IsCorrect) values('Nothing',0);
exec dbo.InsertQuizQuestion 'The Walking Dead TV show is based of what?',3,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('October 31st, 2009',0);
insert into @answers(Content, IsCorrect) values('October 31st, 2010',1);
insert into @answers(Content, IsCorrect) values('October 31st, 2011',0);
insert into @answers(Content, IsCorrect) values('October 15th, 2010',0);
exec dbo.InsertQuizQuestion 'When did the Walking Dead premier?',3,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Robert Kirkman',0);
insert into @answers(Content, IsCorrect) values('Tony Moore',0);
insert into @answers(Content, IsCorrect) values('Charlie Adlard',0);
insert into @answers(Content, IsCorrect) values('Frank Darabont',1);
exec dbo.InsertQuizQuestion 'What filmmaker was originally the writer, director and executive producer of The Walking Dead?',3,15, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('33',0);
insert into @answers(Content, IsCorrect) values('45',0);
insert into @answers(Content, IsCorrect) values('15',0);
insert into @answers(Content, IsCorrect) values('22',1);
exec dbo.InsertQuizQuestion 'What number Shane had on his chain?',4,15, @answers;