insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(46, 'Which of these countries are part of NATO? (not all members are included in this quiz)', 4)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Belgium', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Canada', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Denmark', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'France', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Iceland', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Italy', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Luxembourg', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Netherlands', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Norway', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Portugal', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'United Kingdom', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'United States', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Greece', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Turkey', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Germany', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Spain', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Sweden', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Finland', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Switzerland', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Morocco', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Tunisia', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(46, 'Algeria', 0)