insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(51, 'What are the four fundamental states of matter?', 1)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Solid', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Liquid', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Gas', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Plasma', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Conductor', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Mesophase', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Glass', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Amorphous', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Crystal', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Nematic', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Magnet', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(51, 'Oxide', 0)