insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(43, 'Select all main characters from Firefly.', 1)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Mal', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Jane', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'River', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Simon', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Wash', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Zoe', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Book', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Inara', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Kaylee', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Saffron', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Badger', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Niska', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Jubal', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Regan', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Higgins', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'Dobson', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(43, 'McGuinness', 0)
