declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('United States and Japan',1);
insert into @answers(Content, IsCorrect) values('United Kingdom and Japan',0);
insert into @answers(Content, IsCorrect) values('Germany and China',0);
insert into @answers(Content, IsCorrect) values('Australia and China',0);
exec dbo.InsertQuizQuestion 'Who were two major opposing forces of the Pacific Theater? ',2,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1939',0);
insert into @answers(Content, IsCorrect) values('1941',1);
insert into @answers(Content, IsCorrect) values('1944',0);
insert into @answers(Content, IsCorrect) values('1950',0);
exec dbo.InsertQuizQuestion 'What year did Japan attack Pearl Harbor?',2,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Space for its population',0);
insert into @answers(Content, IsCorrect) values('To exert dominance',0);
insert into @answers(Content, IsCorrect) values('To capture other militaries',0);
insert into @answers(Content, IsCorrect) values('To capture economic resources',1);
exec dbo.InsertQuizQuestion 'For what major reason did Japan begin expanding its empire in the Pacific?',4,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Guam',1);
insert into @answers(Content, IsCorrect) values('Hawaii',0);
insert into @answers(Content, IsCorrect) values('Bermuda',0);
insert into @answers(Content, IsCorrect) values('New Zealand',0);
exec dbo.InsertQuizQuestion 'Which of these islands was captured during Japan''s initial attacks?',2,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('China',0);
insert into @answers(Content, IsCorrect) values('China',1);
insert into @answers(Content, IsCorrect) values('Soviet Union',0);
insert into @answers(Content, IsCorrect) values('United States',0);
exec dbo.InsertQuizQuestion 'Which country had Japan been at war with before the Pacific Theater officially began?',3,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('California',0);
insert into @answers(Content, IsCorrect) values('Washington',0);
insert into @answers(Content, IsCorrect) values('Oregon',0);
insert into @answers(Content, IsCorrect) values('Alaska',1);
exec dbo.InsertQuizQuestion 'Which US state other than Hawaii was also attacked by Japan?',3,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Great Japanese Empire',0);
insert into @answers(Content, IsCorrect) values('Greater East Asia Co-Prosperity Sphere',1);
insert into @answers(Content, IsCorrect) values('Pacific Empire',0);
insert into @answers(Content, IsCorrect) values('The Rising Sun',0);
exec dbo.InsertQuizQuestion 'What was the name that Japan gave to its Pacific Empire?',3,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1943',0);
insert into @answers(Content, IsCorrect) values('1945',0);
insert into @answers(Content, IsCorrect) values('1945',1);
insert into @answers(Content, IsCorrect) values('1946',0);
exec dbo.InsertQuizQuestion 'Which year did the Pacific Theater (and World War II) end?',3,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Iwo Jima',1);
insert into @answers(Content, IsCorrect) values('Okinawa',0);
insert into @answers(Content, IsCorrect) values('Palau',0);
insert into @answers(Content, IsCorrect) values('Guam',0);
exec dbo.InsertQuizQuestion 'Which island is featured in the famous Raising the American Flag image?',2,24, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Hirohito',1);
insert into @answers(Content, IsCorrect) values('Taisho',0);
insert into @answers(Content, IsCorrect) values('Akihito',0);
insert into @answers(Content, IsCorrect) values('Musashi',0);
exec dbo.InsertQuizQuestion 'Who was the Emperor of Japan during World War II?',3,24, @answers;