declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('9',0);
insert into @answers(Content, IsCorrect) values('13',0);
insert into @answers(Content, IsCorrect) values('16',0);
insert into @answers(Content, IsCorrect) values('18',1);
exec dbo.InsertQuizQuestion 'A standard golf course has how many holes?',1,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('All holes have a 3 stroke par',1);
insert into @answers(Content, IsCorrect) values('All holes have 3 sand traps',0);
insert into @answers(Content, IsCorrect) values('The course only has 3 holes',0);
insert into @answers(Content, IsCorrect) values('All holes can be completed with only a 3 iron',0);
exec dbo.InsertQuizQuestion 'What makes a course a par 3 course?',1,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('TRUE',1);
insert into @answers(Content, IsCorrect) values('FALSE',0);
insert into @answers(Content, IsCorrect) values('',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuizQuestion 'Sand traps and bunkers are almost always artificially created. True or false?',1,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('United States',0);
insert into @answers(Content, IsCorrect) values('United Kingdom',0);
insert into @answers(Content, IsCorrect) values('Japan',1);
insert into @answers(Content, IsCorrect) values('Australia',0);
exec dbo.InsertQuizQuestion 'Which country has the only courses which feature a par 7 hole?',4,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Number of hazards',0);
insert into @answers(Content, IsCorrect) values('Terrain slopes',1);
insert into @answers(Content, IsCorrect) values('Clubs required to finish',0);
insert into @answers(Content, IsCorrect) values('Number of trees',0);
exec dbo.InsertQuizQuestion 'Other than distance, what else can affect the par rating of a hole?',3,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Fairway',0);
insert into @answers(Content, IsCorrect) values('Teeing ground',1);
insert into @answers(Content, IsCorrect) values('Rough',0);
insert into @answers(Content, IsCorrect) values('Green',0);
exec dbo.InsertQuizQuestion 'What''s the first section of every hole called?',1,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Ladies'' tee',0);
insert into @answers(Content, IsCorrect) values('Senior men''s tee',0);
insert into @answers(Content, IsCorrect) values('Men''s tee',0);
insert into @answers(Content, IsCorrect) values('Tournament tee',1);
exec dbo.InsertQuizQuestion 'What does a black or blue tee marker indicate?',4,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Player cannot touch the ground with the club before swinging',1);
insert into @answers(Content, IsCorrect) values('Player must always play the ball where it lies',0);
insert into @answers(Content, IsCorrect) values('Player takes 2 extra strokes for each hazard',0);
insert into @answers(Content, IsCorrect) values('Player can only choose special clubs to hit with',0);
exec dbo.InsertQuizQuestion 'What is one special rule that applies to a ball in a hazard?',3,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Coastal, sandy area',1);
insert into @answers(Content, IsCorrect) values('Rocky, mountainous area',0);
insert into @answers(Content, IsCorrect) values('Desert area',0);
insert into @answers(Content, IsCorrect) values('Swampy area',0);
exec dbo.InsertQuizQuestion 'What makes a course a links course?',3,25, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Executive',1);
insert into @answers(Content, IsCorrect) values('Professional',0);
insert into @answers(Content, IsCorrect) values('Amateur',0);
insert into @answers(Content, IsCorrect) values('Champion',0);
exec dbo.InsertQuizQuestion 'What is a 9 hole course usually called?',3,25, @answers;