insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(52, 'What are the eight main taxonomic ranks in zoology?', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Domain', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Kingdom', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Phylum', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Class', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Order', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Family', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Genus', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Species', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Linnaeus', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Binomial', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Subfamily', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Tribe', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Taxon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Nomen', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Section', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Series', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Variety', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Form', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(52, 'Taxa', 0)