insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(59, 'Which of these foods should you avoid while wearing braces?', 2)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Popcorn', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Nuts', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Hard taco shells', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Gum', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Sticky/hard candy', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'GIce', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Crunchy chips', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Pretzels', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Hard cookies', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Hard crackers', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Croutons', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Bananas', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Yogurt', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Grapes', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Melons', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Cheese', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Soft cookies', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Mashed potatoes', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(59, 'Peanut butter', 0)