insert into dbo.MinefieldQuestions(minefieldquestionid, content, points) values(38, 'Can you select all the books written by Ernhest Hemingway?', 3)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Sun Also Rises', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'A Farewell to Arms', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'For Whom the Bell Tolls', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Old Man and the Sea', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Garden of Eden', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'A Tale of Two Cities', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'To Kill a Mockingbird', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, '1984', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'Pride and Prejudice', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'Animal Farm', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Little Prince', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Catcher in the Rye', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Great Gatsby', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'The Lord of the Rings', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'Jane Eyre', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'Lord of the Flies', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(38, 'Of Mice and Men', 0)
