insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(48, 'Can you select all of the pitchers inducted to the MLB Hall of Fame?', 4)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Randy Johnson', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Pedro Martinez', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'John Smoltz', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Tom Glavine', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Greg Maddux', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Hank O''Day', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Dennis Eckersley', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Addie Joss', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Bob Lemon', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Babe Ruthe', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Dizzy Dean', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Tim Keefe', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Ty Cobb', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Walter Johnson', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Hank Aaron', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Rod Carew', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Joe Morgan', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(48, 'Johnny Bench', 0)