declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Paul',0);
insert into @answers(Content, IsCorrect) values('Yancy',1);
insert into @answers(Content, IsCorrect) values('Steve',0);
insert into @answers(Content, IsCorrect) values('Lim',0);
exec dbo.InsertQuizQuestion 'What is Fry''s brother''s name?',4,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Turanga',1);
insert into @answers(Content, IsCorrect) values('Nostalya',0);
insert into @answers(Content, IsCorrect) values('Amy',0);
insert into @answers(Content, IsCorrect) values('Larissa',0);
exec dbo.InsertQuizQuestion 'What is Leela''s first name?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Distant uncle and nephew',1);
insert into @answers(Content, IsCorrect) values('Best friends',0);
insert into @answers(Content, IsCorrect) values('Distant grand parent and grand child',0);
insert into @answers(Content, IsCorrect) values('Siblings',0);
exec dbo.InsertQuizQuestion 'How is Fry related to the Professor?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Earth',0);
insert into @answers(Content, IsCorrect) values('Mercury',0);
insert into @answers(Content, IsCorrect) values('Mars',1);
insert into @answers(Content, IsCorrect) values('Saturn',0);
exec dbo.InsertQuizQuestion 'What planet is Amy from?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Diamonds',0);
insert into @answers(Content, IsCorrect) values('Dark matter',1);
insert into @answers(Content, IsCorrect) values('Rubies',0);
insert into @answers(Content, IsCorrect) values('Grass',0);
exec dbo.InsertQuizQuestion 'What kind of material does Nibbler create?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Lawyer',0);
insert into @answers(Content, IsCorrect) values('Accountant',0);
insert into @answers(Content, IsCorrect) values('Dentist',0);
insert into @answers(Content, IsCorrect) values('Physician',1);
exec dbo.InsertQuizQuestion 'What is Zoidberg''s job at Planet Express?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('He is his own grandfather',1);
insert into @answers(Content, IsCorrect) values('He doesn''t know',0);
insert into @answers(Content, IsCorrect) values('The Professor',0);
insert into @answers(Content, IsCorrect) values('A random alien',0);
exec dbo.InsertQuizQuestion 'Who is Fry''s grandfather?',4,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('He gets drunk',1);
insert into @answers(Content, IsCorrect) values('He gets angry',0);
insert into @answers(Content, IsCorrect) values('He gets tired',0);
insert into @answers(Content, IsCorrect) values('',0);
exec dbo.InsertQuizQuestion 'When Bender doesn''t drink alcohol, what happens?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Spock',0);
insert into @answers(Content, IsCorrect) values('Kirk',1);
insert into @answers(Content, IsCorrect) values('McCoy',0);
insert into @answers(Content, IsCorrect) values('Scotty',0);
exec dbo.InsertQuizQuestion 'Which Star Trek character was Zapp Brannigan based on?',3,22, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Sprinting',0);
insert into @answers(Content, IsCorrect) values('Swimming',0);
insert into @answers(Content, IsCorrect) values('Weightlifting',0);
insert into @answers(Content, IsCorrect) values('Limbo',1);
exec dbo.InsertQuizQuestion 'Hermes was in the Olympics for which sport?',3,22, @answers;