declare @answers as dbo.AnswerType;

delete from @answers;
insert into @answers(Content, IsCorrect) values('Sunday',0);
insert into @answers(Content, IsCorrect) values('Monday',1);
insert into @answers(Content, IsCorrect) values('Wednesday',0);
insert into @answers(Content, IsCorrect) values('Friday',0);
exec dbo.InsertQuizQuestion 'Which day is the busiest day for food trucks?',4,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Roach coaches',1);
insert into @answers(Content, IsCorrect) values('Food Trucks',0);
insert into @answers(Content, IsCorrect) values('Food Wheels',0);
insert into @answers(Content, IsCorrect) values('Restaurants on Wheels',0);
exec dbo.InsertQuizQuestion 'In the 1960s, construction sites commonly referred to food trucks as what?',2,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1970',0);
insert into @answers(Content, IsCorrect) values('1974',1);
insert into @answers(Content, IsCorrect) values('1980',0);
insert into @answers(Content, IsCorrect) values('1982',0);
exec dbo.InsertQuizQuestion 'The USA''s first taco truck opened in what year?',4,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Hot Sandwiches',1);
insert into @answers(Content, IsCorrect) values('Mexican Food',0);
insert into @answers(Content, IsCorrect) values('Soups',0);
insert into @answers(Content, IsCorrect) values('Pasta',0);
exec dbo.InsertQuizQuestion 'What is the most popular food truck food?',2,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('1936',1);
insert into @answers(Content, IsCorrect) values('1940',0);
insert into @answers(Content, IsCorrect) values('1942',0);
insert into @answers(Content, IsCorrect) values('1945',0);
exec dbo.InsertQuizQuestion 'The Oscar Mayer''s Weiner Mobile first rolled out in what year?',3,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Snack Vans',0);
insert into @answers(Content, IsCorrect) values('Food Trucks',0);
insert into @answers(Content, IsCorrect) values('Mobile Canteens',0);
insert into @answers(Content, IsCorrect) values('Cantines ',1);
exec dbo.InsertQuizQuestion 'In Quebec, what are food trucks more commonly known as?',2,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Los Angeles',0);
insert into @answers(Content, IsCorrect) values('Orlando',1);
insert into @answers(Content, IsCorrect) values('Portland',0);
insert into @answers(Content, IsCorrect) values('San Francisco',0);
exec dbo.InsertQuizQuestion 'Which city has the most food truck per capita?',4,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('August 1st, 2010',0);
insert into @answers(Content, IsCorrect) values('August 15th, 2010',1);
insert into @answers(Content, IsCorrect) values('September 1st, 2010',0);
insert into @answers(Content, IsCorrect) values('September 15th, 2010',0);
exec dbo.InsertQuizQuestion 'The Great Food Truck Race originally aired on what date?',3,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('2007',0);
insert into @answers(Content, IsCorrect) values('2008',0);
insert into @answers(Content, IsCorrect) values('2009',0);
insert into @answers(Content, IsCorrect) values('2010',1);
exec dbo.InsertQuizQuestion 'What year did Los Angeles start ranking food trucks with letter grades like restaurants?',3,14, @answers;
delete from @answers;
insert into @answers(Content, IsCorrect) values('Chef',1);
insert into @answers(Content, IsCorrect) values('Food Truck',0);
insert into @answers(Content, IsCorrect) values('The Great Food Truck Race ',0);
insert into @answers(Content, IsCorrect) values('Chef Jon',0);
exec dbo.InsertQuizQuestion 'What movie focuses on a chef who loses his restaurant job and starts up a food truck?',2,14, @answers;