insert into dbo.minefieldquestions(minefieldquestionid, content, points) values(44, 'What are the most common names of quadrilaterals?', 2)

insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Trapezium', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Trapezoid', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Parallelogram', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Rectangle', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Square', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Kite', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Rhombus', 1)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Triangle', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Circle', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Equilateral', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Crescent', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Oval', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Quatrefoil', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Pentagon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Hexagon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Octagon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Decagon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Nonagon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Heptagon', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Ellipse', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Leaf', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Bubble Oval', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Star Badge', 0)
insert into dbo.minefieldanswers(minefieldquestionid, content, iscorrect) values(44, 'Anchor', 0)
