//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwolipsDating.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwolipsDating.Utilities.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your gift notifications from being removed. If this continues, contact support..
        /// </summary>
        internal static string AllGiftNotificationsNotRemoved {
            get {
                return ResourceManager.GetString("AllGiftNotificationsNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your answer from being submitted. If this continues, contact support..
        /// </summary>
        internal static string AnswerNotSubmitted {
            get {
                return ResourceManager.GetString("AnswerNotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot favorite your own profile..
        /// </summary>
        internal static string CannotFavoriteOwnProfile {
            get {
                return ResourceManager.GetString("CannotFavoriteOwnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot ignore yourself..
        /// </summary>
        internal static string CannotIgnoreSelf {
            get {
                return ResourceManager.GetString("CannotIgnoreSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to confirm your email address first..
        /// </summary>
        internal static string EmailAddressNotConfirmed {
            get {
                return ResourceManager.GetString("EmailAddressNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented you from toggling the favorite profile status. If this continues, contact support..
        /// </summary>
        internal static string FavoriteProfileNotSaved {
            get {
                return ResourceManager.GetString("FavoriteProfileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your gift notification from being removed. If this continues, contact support..
        /// </summary>
        internal static string GiftNotificationNotRemoved {
            get {
                return ResourceManager.GetString("GiftNotificationNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your gift from being sent. If this continues, contact support..
        /// </summary>
        internal static string GiftNotSent {
            get {
                return ResourceManager.GetString("GiftNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to purchase the gift. Contact support if you continue seeing this..
        /// </summary>
        internal static string GiftPurchaseFailed {
            get {
                return ResourceManager.GetString("GiftPurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your from toggling the ignored user status. If this continues, contact support..
        /// </summary>
        internal static string IgnoredUserNotSaved {
            get {
                return ResourceManager.GetString("IgnoredUserNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your message from being sent. If this continues, contact support..
        /// </summary>
        internal static string MessageNotSent {
            get {
                return ResourceManager.GetString("MessageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your profile image from being changed. If this continues, contact support..
        /// </summary>
        internal static string ProfileImageNotChanged {
            get {
                return ResourceManager.GetString("ProfileImageNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your profile from being created. If this continues, contact support..
        /// </summary>
        internal static string ProfileNotCreated {
            get {
                return ResourceManager.GetString("ProfileNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your question violation from being sent. If this continues, contact support..
        /// </summary>
        internal static string QuestionViolationNotSaved {
            get {
                return ResourceManager.GetString("QuestionViolationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your review from being saved. If this continues, contact support..
        /// </summary>
        internal static string ReviewNotSaved {
            get {
                return ResourceManager.GetString("ReviewNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your review violation from being sent. If this continues, contact support..
        /// </summary>
        internal static string ReviewViolationNotSaved {
            get {
                return ResourceManager.GetString("ReviewViolationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your self summary from being saved. If this continues, contact support..
        /// </summary>
        internal static string SelfSummaryNotSaved {
            get {
                return ResourceManager.GetString("SelfSummaryNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your summary of what you are doing from being saved. If this continues, contact support..
        /// </summary>
        internal static string SummaryOfDoingNotSaved {
            get {
                return ResourceManager.GetString("SummaryOfDoingNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your summary of where you are going from being saved. If this continues, contact support..
        /// </summary>
        internal static string SummaryOfGoingNotSaved {
            get {
                return ResourceManager.GetString("SummaryOfGoingNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your tag suggestion from being saved. If this continues, contact support..
        /// </summary>
        internal static string TagSuggestionNotSaved {
            get {
                return ResourceManager.GetString("TagSuggestionNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select that title because you haven&apos;t obtained it yet..
        /// </summary>
        internal static string TitleNotObtained {
            get {
                return ResourceManager.GetString("TitleNotObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your title from being selected. If this continues, contact support..
        /// </summary>
        internal static string TitleNotSelected {
            get {
                return ResourceManager.GetString("TitleNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to purchase the title. Contact support if you continue seeing this..
        /// </summary>
        internal static string TitlePurchaseFailed {
            get {
                return ResourceManager.GetString("TitlePurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occurred. Contact support if you need assistance..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We already received a violation report by you for this question..
        /// </summary>
        internal static string UserAlreadyReportedQuestion {
            get {
                return ResourceManager.GetString("UserAlreadyReportedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We already received a violation report by you for this review..
        /// </summary>
        internal static string UserAlreadyReportedReview {
            get {
                return ResourceManager.GetString("UserAlreadyReportedReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your image from being deleted. If this continues, contact support..
        /// </summary>
        internal static string UserImageNotDeleted {
            get {
                return ResourceManager.GetString("UserImageNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something prevented your image from being uploaded. If this continues, contact support..
        /// </summary>
        internal static string UserImageNotUploaded {
            get {
                return ResourceManager.GetString("UserImageNotUploaded", resourceCulture);
            }
        }
    }
}
